package com.demo.common.test;

import com.demo.common.test.BaseAdminRegister;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRegister extends BaseAdminRegister<AdminRegister> {
	
}
