package com.demo.common.test;

import com.demo.common.test.BaseAdminPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminPermission extends BaseAdminPermission<AdminPermission> {
	
}
