package com.demo.common.test;

import com.demo.common.test.BaseAuthRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthRolePermission extends BaseAuthRolePermission<AuthRolePermission> {
	
}
