package com.demo.common.test;

import com.demo.common.test.BaseBargainGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargainGoods extends BaseBargainGoods<BargainGoods> {
	
}
