package com.demo.common.test;

import com.demo.common.test.BaseBargainUserOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargainUserOrder extends BaseBargainUserOrder<BargainUserOrder> {
	
}
