package com.demo.common.test;

import com.demo.common.test.BaseBargainOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargainOrder extends BaseBargainOrder<BargainOrder> {
	
}
