package com.demo.common.test;

import com.demo.common.test.BaseBargainSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargainSetting extends BaseBargainSetting<BargainSetting> {
	
}
