package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMailSetting<M extends BaseMailSetting<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 发件人邮箱
	 */
	public void setSendMail(java.lang.String sendMail) {
		set("send_mail", sendMail);
	}
	
	/**
	 * 发件人邮箱
	 */
	public java.lang.String getSendMail() {
		return getStr("send_mail");
	}

	/**
	 * 授权码
	 */
	public void setSendPwd(java.lang.String sendPwd) {
		set("send_pwd", sendPwd);
	}
	
	/**
	 * 授权码
	 */
	public java.lang.String getSendPwd() {
		return getStr("send_pwd");
	}

	/**
	 * 发件人名称
	 */
	public void setSendName(java.lang.String sendName) {
		set("send_name", sendName);
	}
	
	/**
	 * 发件人名称
	 */
	public java.lang.String getSendName() {
		return getStr("send_name");
	}

	/**
	 * 收件人邮箱 多个用英文逗号隔开
	 */
	public void setReceiveMail(java.lang.String receiveMail) {
		set("receive_mail", receiveMail);
	}
	
	/**
	 * 收件人邮箱 多个用英文逗号隔开
	 */
	public java.lang.String getReceiveMail() {
		return getStr("receive_mail");
	}

	/**
	 * 是否开启邮件通知 0--关闭 1--开启
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 是否开启邮件通知 0--关闭 1--开启
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

}
