package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntegralOrderDetail<M extends BaseIntegralOrderDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 商品数量
	 */
	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	/**
	 * 商品数量
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 此商品的总价
	 */
	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
	}
	
	/**
	 * 此商品的总价
	 */
	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 商品规格
	 */
	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	/**
	 * 商品规格
	 */
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	/**
	 * 商品规格图片
	 */
	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}
	
	/**
	 * 商品规格图片
	 */
	public java.lang.String getPic() {
		return getStr("pic");
	}

	/**
	 * 积分花费
	 */
	public void setPayIntegral(java.lang.Long payIntegral) {
		set("pay_integral", payIntegral);
	}
	
	/**
	 * 积分花费
	 */
	public java.lang.Long getPayIntegral() {
		return getLong("pay_integral");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}
	
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

}
