package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStore<M extends BaseStore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}
	
	public java.lang.Integer getAdminId() {
		return getInt("admin_id");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 回收站：0=否，1=是
	 */
	public void setIsRecycle(java.lang.Integer isRecycle) {
		set("is_recycle", isRecycle);
	}
	
	/**
	 * 回收站：0=否，1=是
	 */
	public java.lang.Integer getIsRecycle() {
		return getInt("is_recycle");
	}

	/**
	 * 微擎公众号id
	 */
	public void setAcid(java.lang.Integer acid) {
		set("acid", acid);
	}
	
	/**
	 * 微擎公众号id
	 */
	public java.lang.Integer getAcid() {
		return getInt("acid");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 微信公众号id
	 */
	public void setWechatPlatformId(java.lang.Integer wechatPlatformId) {
		set("wechat_platform_id", wechatPlatformId);
	}
	
	/**
	 * 微信公众号id
	 */
	public java.lang.Integer getWechatPlatformId() {
		return getInt("wechat_platform_id");
	}

	/**
	 * 微信小程序id
	 */
	public void setWechatAppId(java.lang.Integer wechatAppId) {
		set("wechat_app_id", wechatAppId);
	}
	
	/**
	 * 微信小程序id
	 */
	public java.lang.Integer getWechatAppId() {
		return getInt("wechat_app_id");
	}

	/**
	 * 店铺名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 店铺名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 发货通知模板消息id
	 */
	public void setOrderSendTpl(java.lang.String orderSendTpl) {
		set("order_send_tpl", orderSendTpl);
	}
	
	/**
	 * 发货通知模板消息id
	 */
	public java.lang.String getOrderSendTpl() {
		return getStr("order_send_tpl");
	}

	/**
	 * 联系电话
	 */
	public void setContactTel(java.lang.String contactTel) {
		set("contact_tel", contactTel);
	}
	
	/**
	 * 联系电话
	 */
	public java.lang.String getContactTel() {
		return getStr("contact_tel");
	}

	/**
	 * 是否显示在线客服：0=否，1=是
	 */
	public void setShowCustomerService(java.lang.Integer showCustomerService) {
		set("show_customer_service", showCustomerService);
	}
	
	/**
	 * 是否显示在线客服：0=否，1=是
	 */
	public java.lang.Integer getShowCustomerService() {
		return getInt("show_customer_service");
	}

	public void setCopyright(java.lang.String copyright) {
		set("copyright", copyright);
	}
	
	public java.lang.String getCopyright() {
		return getStr("copyright");
	}

	public void setCopyrightPicUrl(java.lang.String copyrightPicUrl) {
		set("copyright_pic_url", copyrightPicUrl);
	}
	
	public java.lang.String getCopyrightPicUrl() {
		return getStr("copyright_pic_url");
	}

	public void setCopyrightUrl(java.lang.String copyrightUrl) {
		set("copyright_url", copyrightUrl);
	}
	
	public java.lang.String getCopyrightUrl() {
		return getStr("copyright_url");
	}

	/**
	 * 收货时间
	 */
	public void setDeliveryTime(java.lang.Integer deliveryTime) {
		set("delivery_time", deliveryTime);
	}
	
	/**
	 * 收货时间
	 */
	public java.lang.Integer getDeliveryTime() {
		return getInt("delivery_time");
	}

	/**
	 * 售后时间
	 */
	public void setAfterSaleTime(java.lang.Integer afterSaleTime) {
		set("after_sale_time", afterSaleTime);
	}
	
	/**
	 * 售后时间
	 */
	public java.lang.Integer getAfterSaleTime() {
		return getInt("after_sale_time");
	}

	/**
	 * 是否使用公众号支付：0=否，1=是
	 */
	public void setUseWechatPlatformPay(java.lang.Integer useWechatPlatformPay) {
		set("use_wechat_platform_pay", useWechatPlatformPay);
	}
	
	/**
	 * 是否使用公众号支付：0=否，1=是
	 */
	public java.lang.Integer getUseWechatPlatformPay() {
		return getInt("use_wechat_platform_pay");
	}

	/**
	 * 快递鸟商户号
	 */
	public void setKdniaoMchId(java.lang.String kdniaoMchId) {
		set("kdniao_mch_id", kdniaoMchId);
	}
	
	/**
	 * 快递鸟商户号
	 */
	public java.lang.String getKdniaoMchId() {
		return getStr("kdniao_mch_id");
	}

	/**
	 * 快递鸟api key
	 */
	public void setKdniaoApiKey(java.lang.String kdniaoApiKey) {
		set("kdniao_api_key", kdniaoApiKey);
	}
	
	/**
	 * 快递鸟api key
	 */
	public java.lang.String getKdniaoApiKey() {
		return getStr("kdniao_api_key");
	}

	/**
	 * 分类页面样式：1=无侧栏，2=有侧栏
	 */
	public void setCatStyle(java.lang.Integer catStyle) {
		set("cat_style", catStyle);
	}
	
	/**
	 * 分类页面样式：1=无侧栏，2=有侧栏
	 */
	public java.lang.Integer getCatStyle() {
		return getInt("cat_style");
	}

	/**
	 * 首页模块布局
	 */
	public void setHomePageModule(java.lang.String homePageModule) {
		set("home_page_module", homePageModule);
	}
	
	/**
	 * 首页模块布局
	 */
	public java.lang.String getHomePageModule() {
		return getStr("home_page_module");
	}

	/**
	 * 店铺地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 店铺地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 首页分类商品列数
	 */
	public void setCatGoodsCols(java.lang.Integer catGoodsCols) {
		set("cat_goods_cols", catGoodsCols);
	}
	
	/**
	 * 首页分类商品列数
	 */
	public java.lang.Integer getCatGoodsCols() {
		return getInt("cat_goods_cols");
	}

	/**
	 * 未支付订单超时时间
	 */
	public void setOverDay(java.lang.Integer overDay) {
		set("over_day", overDay);
	}
	
	/**
	 * 未支付订单超时时间
	 */
	public java.lang.Integer getOverDay() {
		return getInt("over_day");
	}

	/**
	 * 是否开启自提
	 */
	public void setIsOffline(java.lang.Integer isOffline) {
		set("is_offline", isOffline);
	}
	
	/**
	 * 是否开启自提
	 */
	public java.lang.Integer getIsOffline() {
		return getInt("is_offline");
	}

	/**
	 * 是否开启优惠券
	 */
	public void setIsCoupon(java.lang.Integer isCoupon) {
		set("is_coupon", isCoupon);
	}
	
	/**
	 * 是否开启优惠券
	 */
	public java.lang.Integer getIsCoupon() {
		return getInt("is_coupon");
	}

	/**
	 * 首页分类的商品个数
	 */
	public void setCatGoodsCount(java.lang.Integer catGoodsCount) {
		set("cat_goods_count", catGoodsCount);
	}
	
	/**
	 * 首页分类的商品个数
	 */
	public java.lang.Integer getCatGoodsCount() {
		return getInt("cat_goods_count");
	}

	/**
	 * 发货方式：0=快递或自提，1=仅快递，2=仅自提
	 */
	public void setSendType(java.lang.Integer sendType) {
		set("send_type", sendType);
	}
	
	/**
	 * 发货方式：0=快递或自提，1=仅快递，2=仅自提
	 */
	public java.lang.Integer getSendType() {
		return getInt("send_type");
	}

	/**
	 * 会员等级说明
	 */
	public void setMemberContent(java.lang.String memberContent) {
		set("member_content", memberContent);
	}
	
	/**
	 * 会员等级说明
	 */
	public java.lang.String getMemberContent() {
		return getStr("member_content");
	}

	/**
	 * 首页导航栏个数 0--4个 1--5个
	 */
	public void setNavCount(java.lang.Integer navCount) {
		set("nav_count", navCount);
	}
	
	/**
	 * 首页导航栏个数 0--4个 1--5个
	 */
	public java.lang.Integer getNavCount() {
		return getInt("nav_count");
	}

	/**
	 * 一元抵多少积分
	 */
	public void setIntegral(java.lang.Long integral) {
		set("integral", integral);
	}
	
	/**
	 * 一元抵多少积分
	 */
	public java.lang.Long getIntegral() {
		return getLong("integral");
	}

	/**
	 * 积分使用说明
	 */
	public void setIntegration(java.lang.String integration) {
		set("integration", integration);
	}
	
	/**
	 * 积分使用说明
	 */
	public java.lang.String getIntegration() {
		return getStr("integration");
	}

	/**
	 * 分类分割线   0关闭   1开启
	 */
	public void setCutThread(java.lang.Integer cutThread) {
		set("cut_thread", cutThread);
	}
	
	/**
	 * 分类分割线   0关闭   1开启
	 */
	public java.lang.Integer getCutThread() {
		return getInt("cut_thread");
	}

	/**
	 * 一键拨号开关  0关闭  1开启
	 */
	public void setDial(java.lang.Integer dial) {
		set("dial", dial);
	}
	
	/**
	 * 一键拨号开关  0关闭  1开启
	 */
	public java.lang.Integer getDial() {
		return getInt("dial");
	}

	/**
	 * 拨号图标
	 */
	public void setDialPic(java.lang.String dialPic) {
		set("dial_pic", dialPic);
	}
	
	/**
	 * 拨号图标
	 */
	public java.lang.String getDialPic() {
		return getStr("dial_pic");
	}

	public void setPurchaseFrame(java.lang.Integer purchaseFrame) {
		set("purchase_frame", purchaseFrame);
	}
	
	public java.lang.Integer getPurchaseFrame() {
		return getInt("purchase_frame");
	}

	/**
	 * 推荐商品状态 1：开启 0 ：关闭
	 */
	public void setIsRecommend(java.lang.Integer isRecommend) {
		set("is_recommend", isRecommend);
	}
	
	/**
	 * 推荐商品状态 1：开启 0 ：关闭
	 */
	public java.lang.Integer getIsRecommend() {
		return getInt("is_recommend");
	}

	/**
	 * 推荐商品数量
	 */
	public void setRecommendCount(java.lang.Integer recommendCount) {
		set("recommend_count", recommendCount);
	}
	
	/**
	 * 推荐商品数量
	 */
	public java.lang.Integer getRecommendCount() {
		return getInt("recommend_count");
	}

	/**
	 * 禁用状态：0.未禁用|1.禁用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 禁用状态：0.未禁用|1.禁用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 商城评价开关：0.关闭 1.开启
	 */
	public void setIsComment(java.lang.Integer isComment) {
		set("is_comment", isComment);
	}
	
	/**
	 * 商城评价开关：0.关闭 1.开启
	 */
	public java.lang.Integer getIsComment() {
		return getInt("is_comment");
	}

	/**
	 * 商城商品销量开关：0.关闭 1.开启
	 */
	public void setIsSales(java.lang.Integer isSales) {
		set("is_sales", isSales);
	}
	
	/**
	 * 商城商品销量开关：0.关闭 1.开启
	 */
	public java.lang.Integer getIsSales() {
		return getInt("is_sales");
	}

	/**
	 * 会员价是否显示 0.不显示|1.显示
	 */
	public void setIsMemberPrice(java.lang.Boolean isMemberPrice) {
		set("is_member_price", isMemberPrice);
	}
	
	/**
	 * 会员价是否显示 0.不显示|1.显示
	 */
	public java.lang.Boolean getIsMemberPrice() {
		return get("is_member_price");
	}

	/**
	 * 分销价是否显示 0.不显示|1.显示
	 */
	public void setIsSharePrice(java.lang.Boolean isSharePrice) {
		set("is_share_price", isSharePrice);
	}
	
	/**
	 * 分销价是否显示 0.不显示|1.显示
	 */
	public java.lang.Boolean getIsSharePrice() {
		return get("is_share_price");
	}

	/**
	 * 是否购买会员 0不支持 1支持
	 */
	public void setIsMember(java.lang.Integer isMember) {
		set("is_member", isMember);
	}
	
	/**
	 * 是否购买会员 0不支持 1支持
	 */
	public java.lang.Integer getIsMember() {
		return getInt("is_member");
	}

	/**
	 * 1 电话 2 客服
	 */
	public void setGoodNegotiable(java.lang.String goodNegotiable) {
		set("good_negotiable", goodNegotiable);
	}
	
	/**
	 * 1 电话 2 客服
	 */
	public java.lang.String getGoodNegotiable() {
		return getStr("good_negotiable");
	}

	/**
	 * 是否购买会员 0不支持 1支持
	 */
	public void setBuyMember(java.lang.Integer buyMember) {
		set("buy_member", buyMember);
	}
	
	/**
	 * 是否购买会员 0不支持 1支持
	 */
	public java.lang.Integer getBuyMember() {
		return getInt("buy_member");
	}

	/**
	 * 商城logo
	 */
	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}
	
	/**
	 * 商城logo
	 */
	public java.lang.String getLogo() {
		return getStr("logo");
	}

	/**
	 * 公众号关注组件 0.否 | 1.是
	 */
	public void setIsOfficialAccount(java.lang.Boolean isOfficialAccount) {
		set("is_official_account", isOfficialAccount);
	}
	
	/**
	 * 公众号关注组件 0.否 | 1.是
	 */
	public java.lang.Boolean getIsOfficialAccount() {
		return get("is_official_account");
	}

}
