package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxTitle<M extends BaseWxTitle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 小程序页面路径
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 小程序页面路径
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 商城ID
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	/**
	 * 商城ID
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 小程序页面标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 小程序页面标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setAddtime(java.lang.String addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.String getAddtime() {
		return getStr("addtime");
	}

}
