package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStepSetting<M extends BaseStepSetting<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 规则
	 */
	public void setRule(java.lang.String rule) {
		set("rule", rule);
	}
	
	/**
	 * 规则
	 */
	public java.lang.String getRule() {
		return getStr("rule");
	}

	/**
	 * 小程序标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 小程序标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 最大步数兑换限制
	 */
	public void setConvertMax(java.lang.Integer convertMax) {
		set("convert_max", convertMax);
	}
	
	/**
	 * 最大步数兑换限制
	 */
	public java.lang.Integer getConvertMax() {
		return getInt("convert_max");
	}

	/**
	 * 兑换比率
	 */
	public void setConvertRatio(java.lang.Integer convertRatio) {
		set("convert_ratio", convertRatio);
	}
	
	/**
	 * 兑换比率
	 */
	public java.lang.Integer getConvertRatio() {
		return getInt("convert_ratio");
	}

	/**
	 * 邀请比率
	 */
	public void setInviteRatio(java.lang.Integer inviteRatio) {
		set("invite_ratio", inviteRatio);
	}
	
	/**
	 * 邀请比率
	 */
	public java.lang.Integer getInviteRatio() {
		return getInt("invite_ratio");
	}

	/**
	 * 0-24
	 */
	public void setRemindTime(java.lang.String remindTime) {
		set("remind_time", remindTime);
	}
	
	/**
	 * 0-24
	 */
	public java.lang.String getRemindTime() {
		return getStr("remind_time");
	}

	/**
	 * 活动规则
	 */
	public void setActivityRule(java.lang.String activityRule) {
		set("activity_rule", activityRule);
	}
	
	/**
	 * 活动规则
	 */
	public java.lang.String getActivityRule() {
		return getStr("activity_rule");
	}

	/**
	 * 转发标题
	 */
	public void setShareTitle(java.lang.String shareTitle) {
		set("share_title", shareTitle);
	}
	
	/**
	 * 转发标题
	 */
	public java.lang.String getShareTitle() {
		return getStr("share_title");
	}

	/**
	 * 全国排行限制
	 */
	public void setRankingNum(java.lang.Integer rankingNum) {
		set("ranking_num", rankingNum);
	}
	
	/**
	 * 全国排行限制
	 */
	public java.lang.Integer getRankingNum() {
		return getInt("ranking_num");
	}

	/**
	 * 海报文字
	 */
	public void setQrcodeTitle(java.lang.String qrcodeTitle) {
		set("qrcode_title", qrcodeTitle);
	}
	
	/**
	 * 海报文字
	 */
	public java.lang.String getQrcodeTitle() {
		return getStr("qrcode_title");
	}

}
