package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBanner<M extends BaseBanner<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商城id
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	/**
	 * 商城id
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
	}
	
	public java.lang.String getPicUrl() {
		return getStr("pic_url");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setPageUrl(java.lang.String pageUrl) {
		set("page_url", pageUrl);
	}
	
	public java.lang.String getPageUrl() {
		return getStr("page_url");
	}

	/**
	 * 排序，升序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序，升序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	/**
	 * 添加时间
	 */
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 是否删除：0=未删除，1=已删除
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除：0=未删除，1=已删除
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 类型 【1=> 商城，2=> 拼团】
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 类型 【1=> 商城，2=> 拼团】
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setOpenType(java.lang.String openType) {
		set("open_type", openType);
	}
	
	public java.lang.String getOpenType() {
		return getStr("open_type");
	}

}
