package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderExpress<M extends BaseOrderExpress<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 订单类型 0--商城订单 1--秒杀订单 2--拼团订单 
	 */
	public void setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
	}
	
	/**
	 * 订单类型 0--商城订单 1--秒杀订单 2--拼团订单 
	 */
	public java.lang.Integer getOrderType() {
		return getInt("order_type");
	}

	/**
	 * 快递公司编码
	 */
	public void setExpressCode(java.lang.String expressCode) {
		set("express_code", expressCode);
	}
	
	/**
	 * 快递公司编码
	 */
	public java.lang.String getExpressCode() {
		return getStr("express_code");
	}

	/**
	 * 快递鸟id
	 */
	public void setEBusinessID(java.lang.String EBusinessID) {
		set("EBusinessID", EBusinessID);
	}
	
	/**
	 * 快递鸟id
	 */
	public java.lang.String getEBusinessID() {
		return getStr("EBusinessID");
	}

	public void setOrder(java.lang.String order) {
		set("order", order);
	}
	
	public java.lang.String getOrder() {
		return getStr("order");
	}

	public void setPrintTeplate(java.lang.String printTeplate) {
		set("printTeplate", printTeplate);
	}
	
	public java.lang.String getPrintTeplate() {
		return getStr("printTeplate");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

}
