package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActionLog<M extends BaseActionLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 操作记录描述
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 操作记录描述
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 记录时间
	 */
	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	/**
	 * 记录时间
	 */
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 操作人姓名
	 */
	public void setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
	}
	
	/**
	 * 操作人姓名
	 */
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	/**
	 * 操作人ID
	 */
	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 操作人ID
	 */
	public java.lang.Integer getAdminId() {
		return getInt("admin_id");
	}

	/**
	 * 操作人IP地址
	 */
	public void setAdminIp(java.lang.String adminIp) {
		set("admin_ip", adminIp);
	}
	
	/**
	 * 操作人IP地址
	 */
	public java.lang.String getAdminIp() {
		return getStr("admin_ip");
	}

	/**
	 * 操作路由
	 */
	public void setRoute(java.lang.String route) {
		set("route", route);
	}
	
	/**
	 * 操作路由
	 */
	public java.lang.String getRoute() {
		return getStr("route");
	}

	/**
	 * 操作类型
	 */
	public void setActionType(java.lang.String actionType) {
		set("action_type", actionType);
	}
	
	/**
	 * 操作类型
	 */
	public java.lang.String getActionType() {
		return getStr("action_type");
	}

	/**
	 * 操作数据ID
	 */
	public void setObjId(java.lang.Integer objId) {
		set("obj_id", objId);
	}
	
	/**
	 * 操作数据ID
	 */
	public java.lang.Integer getObjId() {
		return getInt("obj_id");
	}

	public void setResult(java.lang.String result) {
		set("result", result);
	}
	
	public java.lang.String getResult() {
		return getStr("result");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 日志类型:1.操作日志 2.定时任务日志
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 日志类型:1.操作日志 2.定时任务日志
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
