package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderMessage<M extends BaseOrderMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 类型id 系统消息时为0
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	/**
	 * 类型id 系统消息时为0
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 消息是否已读 0--未读 1--已读
	 */
	public void setIsRead(java.lang.Integer isRead) {
		set("is_read", isRead);
	}
	
	/**
	 * 消息是否已读 0--未读 1--已读
	 */
	public java.lang.Integer getIsRead() {
		return getInt("is_read");
	}

	/**
	 * 是否提示 0--未提示  1--已提示
	 */
	public void setIsSound(java.lang.Integer isSound) {
		set("is_sound", isSound);
	}
	
	/**
	 * 是否提示 0--未提示  1--已提示
	 */
	public java.lang.Integer getIsSound() {
		return getInt("is_sound");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 订单类型  0--已下订单   1--售后订单
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 订单类型  0--已下订单   1--售后订单
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 订单类型 0--商城订单 1--秒杀订单 2--拼团订单 3--预约订单
	 */
	public void setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
	}
	
	/**
	 * 订单类型 0--商城订单 1--秒杀订单 2--拼团订单 3--预约订单
	 */
	public java.lang.Integer getOrderType() {
		return getInt("order_type");
	}

}
