package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStepActivity<M extends BaseStepActivity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 活动标题
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 活动标题
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 奖金池
	 */
	public void setCurrency(java.math.BigDecimal currency) {
		set("currency", currency);
	}
	
	/**
	 * 奖金池
	 */
	public java.math.BigDecimal getCurrency() {
		return get("currency");
	}

	/**
	 * 保证金
	 */
	public void setBailCurrency(java.math.BigDecimal bailCurrency) {
		set("bail_currency", bailCurrency);
	}
	
	/**
	 * 保证金
	 */
	public java.math.BigDecimal getBailCurrency() {
		return get("bail_currency");
	}

	/**
	 * 0关闭 1开启
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 0关闭 1开启
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 挑战布数
	 */
	public void setStepNum(java.lang.Integer stepNum) {
		set("step_num", stepNum);
	}
	
	/**
	 * 挑战布数
	 */
	public java.lang.Integer getStepNum() {
		return getInt("step_num");
	}

	/**
	 * 开放日期，例：2017-08-21
	 */
	public void setOpenDate(java.util.Date openDate) {
		set("open_date", openDate);
	}
	
	/**
	 * 开放日期，例：2017-08-21
	 */
	public java.util.Date getOpenDate() {
		return get("open_date");
	}

	/**
	 * 是否删除
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 0进行中 1 已完成
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 0进行中 1 已完成
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}

}
