package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFxhbSetting<M extends BaseFxhbSetting<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 拆红包所需用户数,最少2人
	 */
	public void setUserNum(java.lang.Integer userNum) {
		set("user_num", userNum);
	}
	
	/**
	 * 拆红包所需用户数,最少2人
	 */
	public java.lang.Integer getUserNum() {
		return getInt("user_num");
	}

	/**
	 * 红包总金额
	 */
	public void setCouponTotalMoney(java.math.BigDecimal couponTotalMoney) {
		set("coupon_total_money", couponTotalMoney);
	}
	
	/**
	 * 红包总金额
	 */
	public java.math.BigDecimal getCouponTotalMoney() {
		return get("coupon_total_money");
	}

	/**
	 * 赠送的优惠券最低消费金额
	 */
	public void setCouponUseMinimum(java.math.BigDecimal couponUseMinimum) {
		set("coupon_use_minimum", couponUseMinimum);
	}
	
	/**
	 * 赠送的优惠券最低消费金额
	 */
	public java.math.BigDecimal getCouponUseMinimum() {
		return get("coupon_use_minimum");
	}

	/**
	 * 红包优惠券有效期
	 */
	public void setCouponExpire(java.lang.Integer couponExpire) {
		set("coupon_expire", couponExpire);
	}
	
	/**
	 * 红包优惠券有效期
	 */
	public java.lang.Integer getCouponExpire() {
		return getInt("coupon_expire");
	}

	/**
	 * 红包分配类型：0=随机，1=平分
	 */
	public void setDistributeType(java.lang.Boolean distributeType) {
		set("distribute_type", distributeType);
	}
	
	/**
	 * 红包分配类型：0=随机，1=平分
	 */
	public java.lang.Boolean getDistributeType() {
		return get("distribute_type");
	}

	/**
	 * 红包到账通知模板消息id
	 */
	public void setTplMsgId(java.lang.String tplMsgId) {
		set("tpl_msg_id", tplMsgId);
	}
	
	/**
	 * 红包到账通知模板消息id
	 */
	public java.lang.String getTplMsgId() {
		return getStr("tpl_msg_id");
	}

	/**
	 * 每个红包有效期,单位：小时
	 */
	public void setGameTime(java.lang.Integer gameTime) {
		set("game_time", gameTime);
	}
	
	/**
	 * 每个红包有效期,单位：小时
	 */
	public java.lang.Integer getGameTime() {
		return getInt("game_time");
	}

	/**
	 * 是否开启活动，0=不开启，1=开启
	 */
	public void setGameOpen(java.lang.Boolean gameOpen) {
		set("game_open", gameOpen);
	}
	
	/**
	 * 是否开启活动，0=不开启，1=开启
	 */
	public java.lang.Boolean getGameOpen() {
		return get("game_open");
	}

	/**
	 * 规则
	 */
	public void setRule(java.lang.String rule) {
		set("rule", rule);
	}
	
	/**
	 * 规则
	 */
	public java.lang.String getRule() {
		return getStr("rule");
	}

	public void setSharePic(java.lang.String sharePic) {
		set("share_pic", sharePic);
	}
	
	public java.lang.String getSharePic() {
		return getStr("share_pic");
	}

	public void setShareTitle(java.lang.String shareTitle) {
		set("share_title", shareTitle);
	}
	
	public java.lang.String getShareTitle() {
		return getStr("share_title");
	}

}
