package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrinter<M extends BasePrinter<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 打印机名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 打印机名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 打印机类型
	 */
	public void setPrinterType(java.lang.String printerType) {
		set("printer_type", printerType);
	}
	
	/**
	 * 打印机类型
	 */
	public java.lang.String getPrinterType() {
		return getStr("printer_type");
	}

	/**
	 * 打印机设置
	 */
	public void setPrinterSetting(java.lang.String printerSetting) {
		set("printer_setting", printerSetting);
	}
	
	/**
	 * 打印机设置
	 */
	public java.lang.String getPrinterSetting() {
		return getStr("printer_setting");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

}
