package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsShare<M extends BaseGoodsShare<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 商品类型 0--拼团
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 商品类型 0--拼团
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 是否单独分销设置：0=否，1=是
	 */
	public void setIndividualShare(java.lang.Integer individualShare) {
		set("individual_share", individualShare);
	}
	
	/**
	 * 是否单独分销设置：0=否，1=是
	 */
	public java.lang.Integer getIndividualShare() {
		return getInt("individual_share");
	}

	/**
	 * 一级分销佣金比例
	 */
	public void setShareCommissionFirst(java.math.BigDecimal shareCommissionFirst) {
		set("share_commission_first", shareCommissionFirst);
	}
	
	/**
	 * 一级分销佣金比例
	 */
	public java.math.BigDecimal getShareCommissionFirst() {
		return get("share_commission_first");
	}

	/**
	 * 二级分销佣金比例
	 */
	public void setShareCommissionSecond(java.math.BigDecimal shareCommissionSecond) {
		set("share_commission_second", shareCommissionSecond);
	}
	
	/**
	 * 二级分销佣金比例
	 */
	public java.math.BigDecimal getShareCommissionSecond() {
		return get("share_commission_second");
	}

	/**
	 * 三级分销佣金比例
	 */
	public void setShareCommissionThird(java.math.BigDecimal shareCommissionThird) {
		set("share_commission_third", shareCommissionThird);
	}
	
	/**
	 * 三级分销佣金比例
	 */
	public java.math.BigDecimal getShareCommissionThird() {
		return get("share_commission_third");
	}

	/**
	 * 佣金配比 0--百分比 1--固定金额
	 */
	public void setShareType(java.lang.Integer shareType) {
		set("share_type", shareType);
	}
	
	/**
	 * 佣金配比 0--百分比 1--固定金额
	 */
	public java.lang.Integer getShareType() {
		return getInt("share_type");
	}

	/**
	 * 自购返利
	 */
	public void setRebate(java.math.BigDecimal rebate) {
		set("rebate", rebate);
	}
	
	/**
	 * 自购返利
	 */
	public java.math.BigDecimal getRebate() {
		return get("rebate");
	}

	/**
	 * 分销设置类型 0.普通设置|1.详细设置
	 */
	public void setAttrSettingType(java.lang.Boolean attrSettingType) {
		set("attr_setting_type", attrSettingType);
	}
	
	/**
	 * 分销设置类型 0.普通设置|1.详细设置
	 */
	public java.lang.Boolean getAttrSettingType() {
		return get("attr_setting_type");
	}

	/**
	 * 关联临时分销佣金ID，秒杀商品设置|拼团阶梯团
	 */
	public void setRelationId(java.lang.Integer relationId) {
		set("relation_id", relationId);
	}
	
	/**
	 * 关联临时分销佣金ID，秒杀商品设置|拼团阶梯团
	 */
	public java.lang.Integer getRelationId() {
		return getInt("relation_id");
	}

}
