package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAddress<M extends BaseAddress<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}
	
	public java.lang.Integer getProvinceId() {
		return getInt("province_id");
	}

	/**
	 * 省份名称
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	/**
	 * 省份名称
	 */
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}
	
	public java.lang.Integer getCityId() {
		return getInt("city_id");
	}

	/**
	 * 城市名称
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	/**
	 * 城市名称
	 */
	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setDistrictId(java.lang.Integer districtId) {
		set("district_id", districtId);
	}
	
	public java.lang.Integer getDistrictId() {
		return getInt("district_id");
	}

	/**
	 * 县区名称
	 */
	public void setDistrict(java.lang.String district) {
		set("district", district);
	}
	
	/**
	 * 县区名称
	 */
	public java.lang.String getDistrict() {
		return getStr("district");
	}

	/**
	 * 详细地址
	 */
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	/**
	 * 详细地址
	 */
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	/**
	 * 是否是默认地址：0=否，1=是
	 */
	public void setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
	}
	
	/**
	 * 是否是默认地址：0=否，1=是
	 */
	public java.lang.Integer getIsDefault() {
		return getInt("is_default");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

}
