package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntegralGoods<M extends BaseIntegralGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 商品名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 售价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 售价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 原价（只做显示用）
	 */
	public void setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
	}
	
	/**
	 * 原价（只做显示用）
	 */
	public java.math.BigDecimal getOriginalPrice() {
		return get("original_price");
	}

	/**
	 * 商品详情，图文
	 */
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	/**
	 * 商品详情，图文
	 */
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	/**
	 * 商品类别
	 */
	public void setCatId(java.lang.Long catId) {
		set("cat_id", catId);
	}
	
	/**
	 * 商品类别
	 */
	public java.lang.Long getCatId() {
		return getLong("cat_id");
	}

	/**
	 * 上架状态：0=下架，1=上架
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 上架状态：0=下架，1=上架
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 规格的库存及价格
	 */
	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	/**
	 * 规格的库存及价格
	 */
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	/**
	 * 排序  升序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序  升序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 虚拟销量
	 */
	public void setVirtualSales(java.lang.Integer virtualSales) {
		set("virtual_sales", virtualSales);
	}
	
	/**
	 * 虚拟销量
	 */
	public java.lang.Integer getVirtualSales() {
		return getInt("virtual_sales");
	}

	/**
	 * 商品缩略图
	 */
	public void setCoverPic(java.lang.String coverPic) {
		set("cover_pic", coverPic);
	}
	
	/**
	 * 商品缩略图
	 */
	public java.lang.String getCoverPic() {
		return getStr("cover_pic");
	}

	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	/**
	 * 重量
	 */
	public void setWeight(java.lang.Double weight) {
		set("weight", weight);
	}
	
	/**
	 * 重量
	 */
	public java.lang.Double getWeight() {
		return getDouble("weight");
	}

	/**
	 * 运费模板ID
	 */
	public void setFreight(java.lang.Long freight) {
		set("freight", freight);
	}
	
	/**
	 * 运费模板ID
	 */
	public java.lang.Long getFreight() {
		return getLong("freight");
	}

	/**
	 * 是否使用规格：0=不使用，1=使用
	 */
	public void setUseAttr(java.lang.Integer useAttr) {
		set("use_attr", useAttr);
	}
	
	/**
	 * 是否使用规格：0=不使用，1=使用
	 */
	public java.lang.Integer getUseAttr() {
		return getInt("use_attr");
	}

	/**
	 * 商品总库存
	 */
	public void setGoodsNum(java.lang.Integer goodsNum) {
		set("goods_num", goodsNum);
	}
	
	/**
	 * 商品总库存
	 */
	public java.lang.Integer getGoodsNum() {
		return getInt("goods_num");
	}

	/**
	 * 所需积分
	 */
	public void setIntegral(java.lang.Integer integral) {
		set("integral", integral);
	}
	
	/**
	 * 所需积分
	 */
	public java.lang.Integer getIntegral() {
		return getInt("integral");
	}

	/**
	 * 商品服务选项
	 */
	public void setService(java.lang.String service) {
		set("service", service);
	}
	
	/**
	 * 商品服务选项
	 */
	public java.lang.String getService() {
		return getStr("service");
	}

	public void setCostPrice(java.math.BigDecimal costPrice) {
		set("cost_price", costPrice);
	}
	
	public java.math.BigDecimal getCostPrice() {
		return get("cost_price");
	}

	public void setGoodsPicList(java.lang.String goodsPicList) {
		set("goods_pic_list", goodsPicList);
	}
	
	public java.lang.String getGoodsPicList() {
		return getStr("goods_pic_list");
	}

	/**
	 * 放置首页：0=不放，1=放
	 */
	public void setIsIndex(java.lang.Integer isIndex) {
		set("is_index", isIndex);
	}
	
	/**
	 * 放置首页：0=不放，1=放
	 */
	public java.lang.Integer getIsIndex() {
		return getInt("is_index");
	}

	/**
	 * 每人限制兑换数量
	 */
	public void setUserNum(java.lang.Integer userNum) {
		set("user_num", userNum);
	}
	
	/**
	 * 每人限制兑换数量
	 */
	public java.lang.Integer getUserNum() {
		return getInt("user_num");
	}

}
