package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLevel<M extends BaseLevel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	/**
	 * 等级名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 等级名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 会员完成订单金额满足则升级
	 */
	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}
	
	/**
	 * 会员完成订单金额满足则升级
	 */
	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	/**
	 * 折扣
	 */
	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	/**
	 * 折扣
	 */
	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	/**
	 * 状态 0--禁用 1--启用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 0--禁用 1--启用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 会员图片
	 */
	public void setImage(java.lang.String image) {
		set("image", image);
	}
	
	/**
	 * 会员图片
	 */
	public java.lang.String getImage() {
		return getStr("image");
	}

	/**
	 * 会员价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 会员价格
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 会员介绍
	 */
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	/**
	 * 会员介绍
	 */
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	/**
	 * 购买之前提示
	 */
	public void setBuyPrompt(java.lang.String buyPrompt) {
		set("buy_prompt", buyPrompt);
	}
	
	/**
	 * 购买之前提示
	 */
	public java.lang.String getBuyPrompt() {
		return getStr("buy_prompt");
	}

	/**
	 * 会员权益(禁用)
	 */
	public void setSynopsis(java.lang.String synopsis) {
		set("synopsis", synopsis);
	}
	
	/**
	 * 会员权益(禁用)
	 */
	public java.lang.String getSynopsis() {
		return getStr("synopsis");
	}

}
