package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtCat<M extends BasePtCat<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 标题名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 标题名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 商城ID
	 */
	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}
	
	/**
	 * 商城ID
	 */
	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

	public void setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
	}
	
	public java.lang.String getPicUrl() {
		return getStr("pic_url");
	}

	/**
	 * 排序 升序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序 升序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setAddtime(java.lang.Long addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Long getAddtime() {
		return getLong("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

}
