package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 商品名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 售价
	 */
	public void setPrice(float price) {
		set("price", price);
	}
	
	/**
	 * 售价
	 */
	public float getPrice() {
		return get("price");
	}

	/**
	 * 原价（只做显示用）
	 */
	public void setOriginalPrice(float originalPrice) {
		set("original_price", originalPrice);
	}
	
	/**
	 * 原价（只做显示用）
	 */
	public float getOriginalPrice() {
		return get("original_price");
	}

	/**
	 * 商品详情，图文
	 */
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	/**
	 * 商品详情，图文
	 */
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	/**
	 * 商品类别
	 */
	public void setCatId(java.lang.Long catId) {
		set("cat_id", catId);
	}
	
	/**
	 * 商品类别
	 */
	public java.lang.Long getCatId() {
		return getLong("cat_id");
	}

	/**
	 * 上架状态：0=下架，1=上架
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 上架状态：0=下架，1=上架
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 规格的库存及价格
	 */
	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	/**
	 * 规格的库存及价格
	 */
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	/**
	 * 商品服务选项
	 */
	public void setService(java.lang.String service) {
		set("service", service);
	}
	
	/**
	 * 商品服务选项
	 */
	public java.lang.String getService() {
		return getStr("service");
	}

	/**
	 * 排序  升序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序  升序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 虚拟销量
	 */
	public void setVirtualSales(java.lang.Integer virtualSales) {
		set("virtual_sales", virtualSales);
	}
	
	/**
	 * 虚拟销量
	 */
	public java.lang.Integer getVirtualSales() {
		return getInt("virtual_sales");
	}

	/**
	 * 商品缩略图
	 */
	public void setCoverPic(java.lang.String coverPic) {
		set("cover_pic", coverPic);
	}
	
	/**
	 * 商品缩略图
	 */
	public java.lang.String getCoverPic() {
		return getStr("cover_pic");
	}

	public void setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
	}
	
	public java.lang.String getVideoUrl() {
		return getStr("video_url");
	}

	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	/**
	 * 是否单独分销设置：0=否，1=是
	 */
	public void setIndividualShare(java.lang.Integer individualShare) {
		set("individual_share", individualShare);
	}
	
	/**
	 * 是否单独分销设置：0=否，1=是
	 */
	public java.lang.Integer getIndividualShare() {
		return getInt("individual_share");
	}

	/**
	 * 一级分销佣金比例
	 */
	public void setShareCommissionFirst(java.math.BigDecimal shareCommissionFirst) {
		set("share_commission_first", shareCommissionFirst);
	}
	
	/**
	 * 一级分销佣金比例
	 */
	public java.math.BigDecimal getShareCommissionFirst() {
		return get("share_commission_first");
	}

	/**
	 * 二级分销佣金比例
	 */
	public void setShareCommissionSecond(java.math.BigDecimal shareCommissionSecond) {
		set("share_commission_second", shareCommissionSecond);
	}
	
	/**
	 * 二级分销佣金比例
	 */
	public java.math.BigDecimal getShareCommissionSecond() {
		return get("share_commission_second");
	}

	/**
	 * 三级分销佣金比例
	 */
	public void setShareCommissionThird(java.math.BigDecimal shareCommissionThird) {
		set("share_commission_third", shareCommissionThird);
	}
	
	/**
	 * 三级分销佣金比例
	 */
	public java.math.BigDecimal getShareCommissionThird() {
		return get("share_commission_third");
	}

	/**
	 * 重量
	 */
	public void setWeight(java.lang.Double weight) {
		set("weight", weight);
	}
	
	/**
	 * 重量
	 */
	public java.lang.Double getWeight() {
		return getDouble("weight");
	}

	/**
	 * 运费模板ID
	 */
	public void setFreight(java.lang.Long freight) {
		set("freight", freight);
	}
	
	/**
	 * 运费模板ID
	 */
	public java.lang.Long getFreight() {
		return getLong("freight");
	}

	/**
	 * 满减
	 */
	public void setFullCut(java.lang.String fullCut) {
		set("full_cut", fullCut);
	}
	
	/**
	 * 满减
	 */
	public java.lang.String getFullCut() {
		return getStr("full_cut");
	}

	/**
	 * 积分设置
	 */
	public void setIntegral(java.lang.String integral) {
		set("integral", integral);
	}
	
	/**
	 * 积分设置
	 */
	public java.lang.String getIntegral() {
		return getStr("integral");
	}

	/**
	 * 是否使用规格：0=不使用，1=使用
	 */
	public void setUseAttr(java.lang.Integer useAttr) {
		set("use_attr", useAttr);
	}
	
	/**
	 * 是否使用规格：0=不使用，1=使用
	 */
	public java.lang.Integer getUseAttr() {
		return getInt("use_attr");
	}

	/**
	 * 佣金配比 0--百分比 1--固定金额
	 */
	public void setShareType(java.lang.Integer shareType) {
		set("share_type", shareType);
	}
	
	/**
	 * 佣金配比 0--百分比 1--固定金额
	 */
	public java.lang.Integer getShareType() {
		return getInt("share_type");
	}

	/**
	 * 是否加入快速购买  0--关闭   1--开启
	 */
	public void setQuickPurchase(java.lang.Integer quickPurchase) {
		set("quick_purchase", quickPurchase);
	}
	
	/**
	 * 是否加入快速购买  0--关闭   1--开启
	 */
	public java.lang.Integer getQuickPurchase() {
		return getInt("quick_purchase");
	}

	/**
	 * 是否加入热销  0--关闭   1--开启
	 */
	public void setHotCakes(java.lang.Integer hotCakes) {
		set("hot_cakes", hotCakes);
	}
	
	/**
	 * 是否加入热销  0--关闭   1--开启
	 */
	public java.lang.Integer getHotCakes() {
		return getInt("hot_cakes");
	}

	public void setCostPrice(java.math.BigDecimal costPrice) {
		set("cost_price", costPrice);
	}
	
	public java.math.BigDecimal getCostPrice() {
		return get("cost_price");
	}

	/**
	 * 是否参与会员折扣  0=参与   1=不参与
	 */
	public void setMemberDiscount(java.lang.Integer memberDiscount) {
		set("member_discount", memberDiscount);
	}
	
	/**
	 * 是否参与会员折扣  0=参与   1=不参与
	 */
	public java.lang.Integer getMemberDiscount() {
		return getInt("member_discount");
	}

	/**
	 * 自购返利
	 */
	public void setRebate(java.math.BigDecimal rebate) {
		set("rebate", rebate);
	}
	
	/**
	 * 自购返利
	 */
	public java.math.BigDecimal getRebate() {
		return get("rebate");
	}

	/**
	 * 入驻商户的id
	 */
	public void setMchId(java.lang.Integer mchId) {
		set("mch_id", mchId);
	}
	
	/**
	 * 入驻商户的id
	 */
	public java.lang.Integer getMchId() {
		return getInt("mch_id");
	}

	/**
	 * 商品总库存
	 */
	public void setGoodsNum(java.lang.Integer goodsNum) {
		set("goods_num", goodsNum);
	}
	
	/**
	 * 商品总库存
	 */
	public java.lang.Integer getGoodsNum() {
		return getInt("goods_num");
	}

	/**
	 * 多商户自己的排序
	 */
	public void setMchSort(java.lang.Integer mchSort) {
		set("mch_sort", mchSort);
	}
	
	/**
	 * 多商户自己的排序
	 */
	public java.lang.Integer getMchSort() {
		return getInt("mch_sort");
	}

	/**
	 * 购买限制:0.不限制|大于0等于限购数量
	 */
	public void setConfineCount(java.lang.Integer confineCount) {
		set("confine_count", confineCount);
	}
	
	/**
	 * 购买限制:0.不限制|大于0等于限购数量
	 */
	public java.lang.Integer getConfineCount() {
		return getInt("confine_count");
	}

	/**
	 * 是否享受会员折扣 0-不享受 1--享受
	 */
	public void setIsLevel(java.lang.Integer isLevel) {
		set("is_level", isLevel);
	}
	
	/**
	 * 是否享受会员折扣 0-不享受 1--享受
	 */
	public java.lang.Integer getIsLevel() {
		return getInt("is_level");
	}

	/**
	 * 类型 0--商城或多商户 2--砍价商品
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 类型 0--商城或多商户 2--砍价商品
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 是否面议 0 不面议 1面议
	 */
	public void setIsNegotiable(java.lang.Integer isNegotiable) {
		set("is_negotiable", isNegotiable);
	}
	
	/**
	 * 是否面议 0 不面议 1面议
	 */
	public java.lang.Integer getIsNegotiable() {
		return getInt("is_negotiable");
	}

	/**
	 * 分销设置类型 0.普通设置|1.详细设置
	 */
	public void setAttrSettingType(java.lang.Boolean attrSettingType) {
		set("attr_setting_type", attrSettingType);
	}
	
	/**
	 * 分销设置类型 0.普通设置|1.详细设置
	 */
	public java.lang.Boolean getAttrSettingType() {
		return get("attr_setting_type");
	}

}
