package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRefundAddress<M extends BaseRefundAddress<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 收件人名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 收件人名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 收件人地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 收件人地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 收件人电话
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 收件人电话
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

}
