package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUploadFile<M extends BaseUploadFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setFileUrl(java.lang.String fileUrl) {
		set("file_url", fileUrl);
	}
	
	public java.lang.String getFileUrl() {
		return getStr("file_url");
	}

	/**
	 * 文件扩展名
	 */
	public void setExtension(java.lang.String extension) {
		set("extension", extension);
	}
	
	/**
	 * 文件扩展名
	 */
	public java.lang.String getExtension() {
		return getStr("extension");
	}

	/**
	 * 文件类型：
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 文件类型：
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 文件大小，字节
	 */
	public void setSize(java.lang.Integer size) {
		set("size", size);
	}
	
	/**
	 * 文件大小，字节
	 */
	public java.lang.Integer getSize() {
		return getInt("size");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 分组id
	 */
	public void setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
	}
	
	/**
	 * 分组id
	 */
	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}

	/**
	 * 商户id
	 */
	public void setMchId(java.lang.Integer mchId) {
		set("mch_id", mchId);
	}
	
	/**
	 * 商户id
	 */
	public java.lang.Integer getMchId() {
		return getInt("mch_id");
	}

}
