package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMch<M extends BaseMch<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	/**
	 * 是否营业：0=否，1=是
	 */
	public void setIsOpen(java.lang.Boolean isOpen) {
		set("is_open", isOpen);
	}
	
	/**
	 * 是否营业：0=否，1=是
	 */
	public java.lang.Boolean getIsOpen() {
		return get("is_open");
	}

	/**
	 * 是否被系统关闭：0=否，1=是
	 */
	public void setIsLock(java.lang.Boolean isLock) {
		set("is_lock", isLock);
	}
	
	/**
	 * 是否被系统关闭：0=否，1=是
	 */
	public java.lang.Boolean getIsLock() {
		return get("is_lock");
	}

	/**
	 * 审核状态：0=待审核，1=审核通过，2=审核不通过
	 */
	public void setReviewStatus(java.lang.Boolean reviewStatus) {
		set("review_status", reviewStatus);
	}
	
	/**
	 * 审核状态：0=待审核，1=审核通过，2=审核不通过
	 */
	public java.lang.Boolean getReviewStatus() {
		return get("review_status");
	}

	/**
	 * 审核结果
	 */
	public void setReviewResult(java.lang.String reviewResult) {
		set("review_result", reviewResult);
	}
	
	/**
	 * 审核结果
	 */
	public java.lang.String getReviewResult() {
		return getStr("review_result");
	}

	/**
	 * 审核时间
	 */
	public void setReviewTime(java.lang.Integer reviewTime) {
		set("review_time", reviewTime);
	}
	
	/**
	 * 审核时间
	 */
	public java.lang.Integer getReviewTime() {
		return getInt("review_time");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}
	
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}
	
	public java.lang.Integer getProvinceId() {
		return getInt("province_id");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}
	
	public java.lang.Integer getCityId() {
		return getInt("city_id");
	}

	public void setDistrictId(java.lang.Integer districtId) {
		set("district_id", districtId);
	}
	
	public java.lang.Integer getDistrictId() {
		return getInt("district_id");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 所售类目
	 */
	public void setMchCommonCatId(java.lang.Integer mchCommonCatId) {
		set("mch_common_cat_id", mchCommonCatId);
	}
	
	/**
	 * 所售类目
	 */
	public java.lang.Integer getMchCommonCatId() {
		return getInt("mch_common_cat_id");
	}

	/**
	 * 客服电话
	 */
	public void setServiceTel(java.lang.String serviceTel) {
		set("service_tel", serviceTel);
	}
	
	/**
	 * 客服电话
	 */
	public java.lang.String getServiceTel() {
		return getStr("service_tel");
	}

	/**
	 * logo
	 */
	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}
	
	/**
	 * logo
	 */
	public java.lang.String getLogo() {
		return getStr("logo");
	}

	/**
	 * 背景图
	 */
	public void setHeaderBg(java.lang.String headerBg) {
		set("header_bg", headerBg);
	}
	
	/**
	 * 背景图
	 */
	public java.lang.String getHeaderBg() {
		return getStr("header_bg");
	}

	/**
	 * 商户手续费
	 */
	public void setTransferRate(java.lang.Integer transferRate) {
		set("transfer_rate", transferRate);
	}
	
	/**
	 * 商户手续费
	 */
	public java.lang.Integer getTransferRate() {
		return getInt("transfer_rate");
	}

	/**
	 * 商户余额
	 */
	public void setAccountMoney(java.math.BigDecimal accountMoney) {
		set("account_money", accountMoney);
	}
	
	/**
	 * 商户余额
	 */
	public java.math.BigDecimal getAccountMoney() {
		return get("account_money");
	}

	/**
	 * 排序：升序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序：升序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 微信号
	 */
	public void setWechatName(java.lang.String wechatName) {
		set("wechat_name", wechatName);
	}
	
	/**
	 * 微信号
	 */
	public java.lang.String getWechatName() {
		return getStr("wechat_name");
	}

	/**
	 * 好店推荐：0.不推荐|1.推荐
	 */
	public void setIsRecommend(java.lang.Integer isRecommend) {
		set("is_recommend", isRecommend);
	}
	
	/**
	 * 好店推荐：0.不推荐|1.推荐
	 */
	public java.lang.Integer getIsRecommend() {
		return getInt("is_recommend");
	}

	/**
	 * 经度
	 */
	public void setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
	}
	
	/**
	 * 经度
	 */
	public java.lang.String getLongitude() {
		return getStr("longitude");
	}

	/**
	 * 纬度
	 */
	public void setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
	}
	
	/**
	 * 纬度
	 */
	public java.lang.String getLatitude() {
		return getStr("latitude");
	}

	/**
	 * 主营范围
	 */
	public void setMainContent(java.lang.String mainContent) {
		set("main_content", mainContent);
	}
	
	/**
	 * 主营范围
	 */
	public java.lang.String getMainContent() {
		return getStr("main_content");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}
	
	public java.lang.String getSummary() {
		return getStr("summary");
	}

}
