package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCoupon<M extends BaseUserCoupon<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setCouponId(java.lang.Integer couponId) {
		set("coupon_id", couponId);
	}
	
	public java.lang.Integer getCouponId() {
		return getInt("coupon_id");
	}

	/**
	 * 自动发放id
	 */
	public void setCouponAutoSendId(java.lang.Integer couponAutoSendId) {
		set("coupon_auto_send_id", couponAutoSendId);
	}
	
	/**
	 * 自动发放id
	 */
	public java.lang.Integer getCouponAutoSendId() {
		return getInt("coupon_auto_send_id");
	}

	/**
	 * 有效期开始时间
	 */
	public void setBeginTime(java.lang.Integer beginTime) {
		set("begin_time", beginTime);
	}
	
	/**
	 * 有效期开始时间
	 */
	public java.lang.Integer getBeginTime() {
		return getInt("begin_time");
	}

	/**
	 * 有效期结束时间
	 */
	public void setEndTime(java.lang.Integer endTime) {
		set("end_time", endTime);
	}
	
	/**
	 * 有效期结束时间
	 */
	public java.lang.Integer getEndTime() {
		return getInt("end_time");
	}

	/**
	 * 是否已过期：0=未过期，1=已过期
	 */
	public void setIsExpire(java.lang.Integer isExpire) {
		set("is_expire", isExpire);
	}
	
	/**
	 * 是否已过期：0=未过期，1=已过期
	 */
	public java.lang.Integer getIsExpire() {
		return getInt("is_expire");
	}

	/**
	 * 是否已使用：0=未使用，1=已使用
	 */
	public void setIsUse(java.lang.Integer isUse) {
		set("is_use", isUse);
	}
	
	/**
	 * 是否已使用：0=未使用，1=已使用
	 */
	public java.lang.Integer getIsUse() {
		return getInt("is_use");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 领取类型 0--平台发放 1--自动发放 2--领券中心领取
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 领取类型 0--平台发放 1--自动发放 2--领券中心领取
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 兑换支付积分数量
	 */
	public void setIntegral(java.lang.Integer integral) {
		set("integral", integral);
	}
	
	/**
	 * 兑换支付积分数量
	 */
	public java.lang.Integer getIntegral() {
		return getInt("integral");
	}

	/**
	 * 兑换支付价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 兑换支付价格
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

}
