package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCash<M extends BaseCash<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 提现金额
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 提现金额
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 申请状态 0--申请中 1--确认申请 2--已打款 3--驳回  5--余额通过
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 申请状态 0--申请中 1--确认申请 2--已打款 3--驳回  5--余额通过
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 付款
	 */
	public void setPayTime(java.lang.Integer payTime) {
		set("pay_time", payTime);
	}
	
	/**
	 * 付款
	 */
	public java.lang.Integer getPayTime() {
		return getInt("pay_time");
	}

	/**
	 * 支付方式 0--微信支付  1--支付宝  2--银行卡  3--余额
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 支付方式 0--微信支付  1--支付宝  2--银行卡  3--余额
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 支付宝账号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 支付宝账号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 支付宝姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 支付宝姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 开户行名称
	 */
	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}
	
	/**
	 * 开户行名称
	 */
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	/**
	 * 打款方式 0--之前未统计的 1--微信自动打款 2--手动打款
	 */
	public void setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
	}
	
	/**
	 * 打款方式 0--之前未统计的 1--微信自动打款 2--手动打款
	 */
	public java.lang.Integer getPayType() {
		return getInt("pay_type");
	}

	/**
	 * 微信自动打款订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}
	
	/**
	 * 微信自动打款订单号
	 */
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 提现手续费
	 */
	public void setServiceCharge(java.math.BigDecimal serviceCharge) {
		set("service_charge", serviceCharge);
	}
	
	/**
	 * 提现手续费
	 */
	public java.math.BigDecimal getServiceCharge() {
		return get("service_charge");
	}

}
