package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtOrder<M extends BasePtOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}
	
	/**
	 * 订单号
	 */
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 订单总费用(包含运费）
	 */
	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
	}
	
	/**
	 * 订单总费用(包含运费）
	 */
	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	/**
	 * 实际支付总费用(含运费）
	 */
	public void setPayPrice(java.math.BigDecimal payPrice) {
		set("pay_price", payPrice);
	}
	
	/**
	 * 实际支付总费用(含运费）
	 */
	public java.math.BigDecimal getPayPrice() {
		return get("pay_price");
	}

	/**
	 * 运费
	 */
	public void setExpressPrice(java.math.BigDecimal expressPrice) {
		set("express_price", expressPrice);
	}
	
	/**
	 * 运费
	 */
	public java.math.BigDecimal getExpressPrice() {
		return get("express_price");
	}

	/**
	 * 收货人姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 收货人姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 收货人手机
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 收货人手机
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 收货地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 收货地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 订单备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 订单备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 支付状态：0=未支付，1=已支付
	 */
	public void setIsPay(java.lang.Integer isPay) {
		set("is_pay", isPay);
	}
	
	/**
	 * 支付状态：0=未支付，1=已支付
	 */
	public java.lang.Integer getIsPay() {
		return getInt("is_pay");
	}

	/**
	 * 支付方式：1=微信支付
	 */
	public void setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
	}
	
	/**
	 * 支付方式：1=微信支付
	 */
	public java.lang.Integer getPayType() {
		return getInt("pay_type");
	}

	/**
	 * 支付时间
	 */
	public void setPayTime(java.lang.Integer payTime) {
		set("pay_time", payTime);
	}
	
	/**
	 * 支付时间
	 */
	public java.lang.Integer getPayTime() {
		return getInt("pay_time");
	}

	/**
	 * 发货状态：0=未发货，1=已发货
	 */
	public void setIsSend(java.lang.Integer isSend) {
		set("is_send", isSend);
	}
	
	/**
	 * 发货状态：0=未发货，1=已发货
	 */
	public java.lang.Integer getIsSend() {
		return getInt("is_send");
	}

	/**
	 * 发货时间
	 */
	public void setSendTime(java.lang.Integer sendTime) {
		set("send_time", sendTime);
	}
	
	/**
	 * 发货时间
	 */
	public java.lang.Integer getSendTime() {
		return getInt("send_time");
	}

	/**
	 * 物流公司
	 */
	public void setExpress(java.lang.String express) {
		set("express", express);
	}
	
	/**
	 * 物流公司
	 */
	public java.lang.String getExpress() {
		return getStr("express");
	}

	public void setExpressNo(java.lang.String expressNo) {
		set("express_no", expressNo);
	}
	
	public java.lang.String getExpressNo() {
		return getStr("express_no");
	}

	/**
	 * 确认收货状态：0=未确认，1=已确认收货
	 */
	public void setIsConfirm(java.lang.Integer isConfirm) {
		set("is_confirm", isConfirm);
	}
	
	/**
	 * 确认收货状态：0=未确认，1=已确认收货
	 */
	public java.lang.Integer getIsConfirm() {
		return getInt("is_confirm");
	}

	/**
	 * 确认收货时间
	 */
	public void setConfirmTime(java.lang.Integer confirmTime) {
		set("confirm_time", confirmTime);
	}
	
	/**
	 * 确认收货时间
	 */
	public java.lang.Integer getConfirmTime() {
		return getInt("confirm_time");
	}

	/**
	 * 是否已评价：0=未评价，1=已评价
	 */
	public void setIsComment(java.lang.Integer isComment) {
		set("is_comment", isComment);
	}
	
	/**
	 * 是否已评价：0=未评价，1=已评价
	 */
	public java.lang.Integer getIsComment() {
		return getInt("is_comment");
	}

	/**
	 * 是否申请取消订单：0=否，1=申请取消订单
	 */
	public void setApplyDelete(java.lang.Integer applyDelete) {
		set("apply_delete", applyDelete);
	}
	
	/**
	 * 是否申请取消订单：0=否，1=申请取消订单
	 */
	public java.lang.Integer getApplyDelete() {
		return getInt("apply_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 收货地址信息，json格式
	 */
	public void setAddressData(java.lang.String addressData) {
		set("address_data", addressData);
	}
	
	/**
	 * 收货地址信息，json格式
	 */
	public java.lang.String getAddressData() {
		return getStr("address_data");
	}

	/**
	 * 是否团购
	 */
	public void setIsGroup(java.lang.Integer isGroup) {
		set("is_group", isGroup);
	}
	
	/**
	 * 是否团购
	 */
	public java.lang.Integer getIsGroup() {
		return getInt("is_group");
	}

	/**
	 * 团ID【0=> 团长ID】
	 */
	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 团ID【0=> 团长ID】
	 */
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	/**
	 * 团长优惠
	 */
	public void setColonel(java.math.BigDecimal colonel) {
		set("colonel", colonel);
	}
	
	/**
	 * 团长优惠
	 */
	public java.math.BigDecimal getColonel() {
		return get("colonel");
	}

	/**
	 * 是否成团
	 */
	public void setIsSuccess(java.lang.Integer isSuccess) {
		set("is_success", isSuccess);
	}
	
	/**
	 * 是否成团
	 */
	public java.lang.Integer getIsSuccess() {
		return getInt("is_success");
	}

	/**
	 * 成团时间
	 */
	public void setSuccessTime(java.lang.Long successTime) {
		set("success_time", successTime);
	}
	
	/**
	 * 成团时间
	 */
	public java.lang.Long getSuccessTime() {
		return getLong("success_time");
	}

	/**
	 * 拼团状态【1=> 待付款，2= 拼团中，3=拼团成功，4=拼团失败】
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 拼团状态【1=> 待付款，2= 拼团中，3=拼团成功，4=拼团失败】
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 是否退款
	 */
	public void setIsReturnd(java.lang.Integer isReturnd) {
		set("is_returnd", isReturnd);
	}
	
	/**
	 * 是否退款
	 */
	public java.lang.Integer getIsReturnd() {
		return getInt("is_returnd");
	}

	/**
	 * 是否取消
	 */
	public void setIsCancel(java.lang.Integer isCancel) {
		set("is_cancel", isCancel);
	}
	
	/**
	 * 是否取消
	 */
	public java.lang.Integer getIsCancel() {
		return getInt("is_cancel");
	}

	/**
	 * 拼团限时
	 */
	public void setLimitTime(java.lang.Long limitTime) {
		set("limit_time", limitTime);
	}
	
	/**
	 * 拼团限时
	 */
	public java.lang.Long getLimitTime() {
		return getLong("limit_time");
	}

	/**
	 * 备注
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 商家留言
	 */
	public void setWords(java.lang.String words) {
		set("words", words);
	}
	
	/**
	 * 商家留言
	 */
	public java.lang.String getWords() {
		return getStr("words");
	}

	/**
	 * 自提店铺
	 */
	public void setShopId(java.lang.Long shopId) {
		set("shop_id", shopId);
	}
	
	/**
	 * 自提店铺
	 */
	public java.lang.Long getShopId() {
		return getLong("shop_id");
	}

	/**
	 * 拿货方式
	 */
	public void setOffline(java.lang.Integer offline) {
		set("offline", offline);
	}
	
	/**
	 * 拿货方式
	 */
	public java.lang.Integer getOffline() {
		return getInt("offline");
	}

	/**
	 * 核销员ID
	 */
	public void setClerkId(java.lang.Long clerkId) {
		set("clerk_id", clerkId);
	}
	
	/**
	 * 核销员ID
	 */
	public java.lang.Long getClerkId() {
		return getLong("clerk_id");
	}

	/**
	 * 是否发放佣金
	 */
	public void setIsPrice(java.lang.Integer isPrice) {
		set("is_price", isPrice);
	}
	
	/**
	 * 是否发放佣金
	 */
	public java.lang.Integer getIsPrice() {
		return getInt("is_price");
	}

	/**
	 * 减免的运费
	 */
	public void setExpressPrice1(java.math.BigDecimal expressPrice1) {
		set("express_price_1", expressPrice1);
	}
	
	/**
	 * 减免的运费
	 */
	public java.math.BigDecimal getExpressPrice1() {
		return get("express_price_1");
	}

	/**
	 * 阶级团
	 */
	public void setClassGroup(java.lang.Integer classGroup) {
		set("class_group", classGroup);
	}
	
	/**
	 * 阶级团
	 */
	public java.lang.Integer getClassGroup() {
		return getInt("class_group");
	}

	/**
	 * 是否加入回收站 0--不加入 1--加入
	 */
	public void setIsRecycle(java.lang.Integer isRecycle) {
		set("is_recycle", isRecycle);
	}
	
	/**
	 * 是否加入回收站 0--不加入 1--加入
	 */
	public java.lang.Integer getIsRecycle() {
		return getInt("is_recycle");
	}

	/**
	 * 是否显示 0--不显示 1--显示（软删除）
	 */
	public void setIsShow(java.lang.Integer isShow) {
		set("is_show", isShow);
	}
	
	/**
	 * 是否显示 0--不显示 1--显示（软删除）
	 */
	public java.lang.Integer getIsShow() {
		return getInt("is_show");
	}

	/**
	 * 商家备注
	 */
	public void setSellerComments(java.lang.String sellerComments) {
		set("seller_comments", sellerComments);
	}
	
	/**
	 * 商家备注
	 */
	public java.lang.String getSellerComments() {
		return getStr("seller_comments");
	}

}
