package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCat<M extends BaseCat<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商城id
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	/**
	 * 商城id
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 上级分类id
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 上级分类id
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 分类名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 分类名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
	}
	
	public java.lang.String getPicUrl() {
		return getStr("pic_url");
	}

	/**
	 * 排序，升序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序，升序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setBigPicUrl(java.lang.String bigPicUrl) {
		set("big_pic_url", bigPicUrl);
	}
	
	public java.lang.String getBigPicUrl() {
		return getStr("big_pic_url");
	}

	/**
	 * 广告图片
	 */
	public void setAdvertPic(java.lang.String advertPic) {
		set("advert_pic", advertPic);
	}
	
	/**
	 * 广告图片
	 */
	public java.lang.String getAdvertPic() {
		return getStr("advert_pic");
	}

	public void setAdvertUrl(java.lang.String advertUrl) {
		set("advert_url", advertUrl);
	}
	
	public java.lang.String getAdvertUrl() {
		return getStr("advert_url");
	}

	/**
	 * 是否显示【1=> 显示，2=> 隐藏】
	 */
	public void setIsShow(java.lang.Integer isShow) {
		set("is_show", isShow);
	}
	
	/**
	 * 是否显示【1=> 显示，2=> 隐藏】
	 */
	public java.lang.Integer getIsShow() {
		return getInt("is_show");
	}

}
