package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrcode<M extends BaseQrcode<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 背景图片
	 */
	public void setQrcodeBg(java.lang.String qrcodeBg) {
		set("qrcode_bg", qrcodeBg);
	}
	
	/**
	 * 背景图片
	 */
	public java.lang.String getQrcodeBg() {
		return getStr("qrcode_bg");
	}

	/**
	 * 头像大小{"w":"","h":""}
	 */
	public void setAvatarSize(java.lang.String avatarSize) {
		set("avatar_size", avatarSize);
	}
	
	/**
	 * 头像大小{"w":"","h":""}
	 */
	public java.lang.String getAvatarSize() {
		return getStr("avatar_size");
	}

	/**
	 * 头像坐标{"x":"","y":""}
	 */
	public void setAvatarPosition(java.lang.String avatarPosition) {
		set("avatar_position", avatarPosition);
	}
	
	/**
	 * 头像坐标{"x":"","y":""}
	 */
	public java.lang.String getAvatarPosition() {
		return getStr("avatar_position");
	}

	/**
	 * 二维码宽度
	 */
	public void setQrcodeSize(java.lang.String qrcodeSize) {
		set("qrcode_size", qrcodeSize);
	}
	
	/**
	 * 二维码宽度
	 */
	public java.lang.String getQrcodeSize() {
		return getStr("qrcode_size");
	}

	/**
	 * 二维码坐标{"x":"","y":""}
	 */
	public void setQrcodePosition(java.lang.String qrcodePosition) {
		set("qrcode_position", qrcodePosition);
	}
	
	/**
	 * 二维码坐标{"x":"","y":""}
	 */
	public java.lang.String getQrcodePosition() {
		return getStr("qrcode_position");
	}

	/**
	 * 字体坐标{"x":"","y":""}
	 */
	public void setFontPosition(java.lang.String fontPosition) {
		set("font_position", fontPosition);
	}
	
	/**
	 * 字体坐标{"x":"","y":""}
	 */
	public java.lang.String getFontPosition() {
		return getStr("font_position");
	}

	/**
	 * 字体设置
{
  "size":大小,
  "color":"r,g,b"
}
	 */
	public void setFont(java.lang.String font) {
		set("font", font);
	}
	
	/**
	 * 字体设置
{
  "size":大小,
  "color":"r,g,b"
}
	 */
	public java.lang.String getFont() {
		return getStr("font");
	}

	/**
	 * 预览图
	 */
	public void setPreview(java.lang.String preview) {
		set("preview", preview);
	}
	
	/**
	 * 预览图
	 */
	public java.lang.String getPreview() {
		return getStr("preview");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

}
