package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtGoods<M extends BasePtGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 商品名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 商品原价
	 */
	public void setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
	}
	
	/**
	 * 商品原价
	 */
	public java.math.BigDecimal getOriginalPrice() {
		return get("original_price");
	}

	/**
	 * 团购价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 团购价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 商品详情，图文
	 */
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	/**
	 * 商品详情，图文
	 */
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	/**
	 * 商品分类
	 */
	public void setCatId(java.lang.Long catId) {
		set("cat_id", catId);
	}
	
	/**
	 * 商品分类
	 */
	public java.lang.Long getCatId() {
		return getLong("cat_id");
	}

	/**
	 * 上架状态【1=> 上架，2=> 下架】
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 上架状态【1=> 上架，2=> 下架】
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 拼团时间/小时
	 */
	public void setGrouptime(java.lang.Integer grouptime) {
		set("grouptime", grouptime);
	}
	
	/**
	 * 拼团时间/小时
	 */
	public java.lang.Integer getGrouptime() {
		return getInt("grouptime");
	}

	/**
	 * 规格的库存及价格
	 */
	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	/**
	 * 规格的库存及价格
	 */
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	/**
	 * 服务选项
	 */
	public void setService(java.lang.String service) {
		set("service", service);
	}
	
	/**
	 * 服务选项
	 */
	public java.lang.String getService() {
		return getStr("service");
	}

	/**
	 * 商品排序 升序
	 */
	public void setSort(java.lang.Long sort) {
		set("sort", sort);
	}
	
	/**
	 * 商品排序 升序
	 */
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	/**
	 * 虚拟销量
	 */
	public void setVirtualSales(java.lang.Long virtualSales) {
		set("virtual_sales", virtualSales);
	}
	
	/**
	 * 虚拟销量
	 */
	public java.lang.Long getVirtualSales() {
		return getLong("virtual_sales");
	}

	/**
	 * 商品缩略图
	 */
	public void setCoverPic(java.lang.String coverPic) {
		set("cover_pic", coverPic);
	}
	
	/**
	 * 商品缩略图
	 */
	public java.lang.String getCoverPic() {
		return getStr("cover_pic");
	}

	/**
	 * 重量
	 */
	public void setWeight(java.lang.Long weight) {
		set("weight", weight);
	}
	
	/**
	 * 重量
	 */
	public java.lang.Long getWeight() {
		return getLong("weight");
	}

	/**
	 * 运费模板ID
	 */
	public void setFreight(java.lang.Long freight) {
		set("freight", freight);
	}
	
	/**
	 * 运费模板ID
	 */
	public java.lang.Long getFreight() {
		return getLong("freight");
	}

	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.lang.Long addtime) {
		set("addtime", addtime);
	}
	
	/**
	 * 添加时间
	 */
	public java.lang.Long getAddtime() {
		return getLong("addtime");
	}

	/**
	 * 是否删除
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 商品成团数
	 */
	public void setGroupNum(java.lang.Long groupNum) {
		set("group_num", groupNum);
	}
	
	/**
	 * 商品成团数
	 */
	public java.lang.Long getGroupNum() {
		return getLong("group_num");
	}

	/**
	 * 是否热卖【0=>热卖1=>不是】
	 */
	public void setIsHot(java.lang.Integer isHot) {
		set("is_hot", isHot);
	}
	
	/**
	 * 是否热卖【0=>热卖1=>不是】
	 */
	public java.lang.Integer getIsHot() {
		return getInt("is_hot");
	}

	/**
	 * 拼团限时
	 */
	public void setLimitTime(java.lang.Long limitTime) {
		set("limit_time", limitTime);
	}
	
	/**
	 * 拼团限时
	 */
	public java.lang.Long getLimitTime() {
		return getLong("limit_time");
	}

	/**
	 * 是否允许单独购买
	 */
	public void setIsOnly(java.lang.Integer isOnly) {
		set("is_only", isOnly);
	}
	
	/**
	 * 是否允许单独购买
	 */
	public java.lang.Integer getIsOnly() {
		return getInt("is_only");
	}

	/**
	 * 是否允许多件购买
	 */
	public void setIsMore(java.lang.Integer isMore) {
		set("is_more", isMore);
	}
	
	/**
	 * 是否允许多件购买
	 */
	public java.lang.Integer getIsMore() {
		return getInt("is_more");
	}

	/**
	 * 团长优惠
	 */
	public void setColonel(java.math.BigDecimal colonel) {
		set("colonel", colonel);
	}
	
	/**
	 * 团长优惠
	 */
	public java.math.BigDecimal getColonel() {
		return get("colonel");
	}

	/**
	 * 限购数量
	 */
	public void setBuyLimit(java.lang.Long buyLimit) {
		set("buy_limit", buyLimit);
	}
	
	/**
	 * 限购数量
	 */
	public java.lang.Long getBuyLimit() {
		return getLong("buy_limit");
	}

	/**
	 * 商品类型【1=> 送货上门，2=> 到店自提，3=> 全部支持】
	 */
	public void setType(java.lang.Long type) {
		set("type", type);
	}
	
	/**
	 * 商品类型【1=> 送货上门，2=> 到店自提，3=> 全部支持】
	 */
	public java.lang.Long getType() {
		return getLong("type");
	}

	/**
	 * 是否使用规格：0=不使用，1=使用
	 */
	public void setUseAttr(java.lang.Integer useAttr) {
		set("use_attr", useAttr);
	}
	
	/**
	 * 是否使用规格：0=不使用，1=使用
	 */
	public java.lang.Integer getUseAttr() {
		return getInt("use_attr");
	}

	/**
	 * 单次限购数量
	 */
	public void setOneBuyLimit(java.lang.Long oneBuyLimit) {
		set("one_buy_limit", oneBuyLimit);
	}
	
	/**
	 * 单次限购数量
	 */
	public java.lang.Long getOneBuyLimit() {
		return getLong("one_buy_limit");
	}

	/**
	 * 支付方式
	 */
	public void setPayment(java.lang.String payment) {
		set("payment", payment);
	}
	
	/**
	 * 支付方式
	 */
	public java.lang.String getPayment() {
		return getStr("payment");
	}

	/**
	 * 是否享受会员折扣 0-不享受 1--享受
	 */
	public void setIsLevel(java.lang.Boolean isLevel) {
		set("is_level", isLevel);
	}
	
	/**
	 * 是否享受会员折扣 0-不享受 1--享受
	 */
	public java.lang.Boolean getIsLevel() {
		return get("is_level");
	}

	/**
	 * 视频url
	 */
	public void setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
	}
	
	/**
	 * 视频url
	 */
	public java.lang.String getVideoUrl() {
		return getStr("video_url");
	}

}
