package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegister<M extends BaseRegister<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setRegisterTime(java.lang.String registerTime) {
		set("register_time", registerTime);
	}
	
	public java.lang.String getRegisterTime() {
		return getStr("register_time");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 连续签到天数
	 */
	public void setContinuation(java.lang.Integer continuation) {
		set("continuation", continuation);
	}
	
	/**
	 * 连续签到天数
	 */
	public java.lang.Integer getContinuation() {
		return getInt("continuation");
	}

	/**
	 * 获得积分
	 */
	public void setIntegral(java.lang.Integer integral) {
		set("integral", integral);
	}
	
	/**
	 * 获得积分
	 */
	public java.lang.Integer getIntegral() {
		return getInt("integral");
	}

	/**
	 * 1--签到
	 */
	public void setType(java.lang.Boolean type) {
		set("type", type);
	}
	
	/**
	 * 1--签到
	 */
	public java.lang.Boolean getType() {
		return get("type");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

}
