package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserLog<M extends BaseUserLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 改变的字段
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 改变的字段
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 改变前字段的值
	 */
	public void setBeforeChange(java.lang.String beforeChange) {
		set("before_change", beforeChange);
	}
	
	/**
	 * 改变前字段的值
	 */
	public java.lang.String getBeforeChange() {
		return getStr("before_change");
	}

	/**
	 * 改变后字段的值
	 */
	public void setAfterChange(java.lang.String afterChange) {
		set("after_change", afterChange);
	}
	
	/**
	 * 改变后字段的值
	 */
	public java.lang.String getAfterChange() {
		return getStr("after_change");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

}
