package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFxhbHongbao<M extends BaseFxhbHongbao<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 拆红包所需用户数,最少2人
	 */
	public void setUserNum(java.lang.Integer userNum) {
		set("user_num", userNum);
	}
	
	/**
	 * 拆红包所需用户数,最少2人
	 */
	public java.lang.Integer getUserNum() {
		return getInt("user_num");
	}

	/**
	 * 红包总金额
	 */
	public void setCouponTotalMoney(java.math.BigDecimal couponTotalMoney) {
		set("coupon_total_money", couponTotalMoney);
	}
	
	/**
	 * 红包总金额
	 */
	public java.math.BigDecimal getCouponTotalMoney() {
		return get("coupon_total_money");
	}

	/**
	 * 分到的红包金额
	 */
	public void setCouponMoney(java.math.BigDecimal couponMoney) {
		set("coupon_money", couponMoney);
	}
	
	/**
	 * 分到的红包金额
	 */
	public java.math.BigDecimal getCouponMoney() {
		return get("coupon_money");
	}

	/**
	 * 红包使用最低消费金额
	 */
	public void setCouponUseMinimum(java.math.BigDecimal couponUseMinimum) {
		set("coupon_use_minimum", couponUseMinimum);
	}
	
	/**
	 * 红包使用最低消费金额
	 */
	public java.math.BigDecimal getCouponUseMinimum() {
		return get("coupon_use_minimum");
	}

	/**
	 * 优惠券有效期，天
	 */
	public void setCouponExpire(java.lang.Integer couponExpire) {
		set("coupon_expire", couponExpire);
	}
	
	/**
	 * 优惠券有效期，天
	 */
	public java.lang.Integer getCouponExpire() {
		return getInt("coupon_expire");
	}

	/**
	 * 红包分配类型：0=随机，1=平分
	 */
	public void setDistributeType(java.lang.Boolean distributeType) {
		set("distribute_type", distributeType);
	}
	
	/**
	 * 红包分配类型：0=随机，1=平分
	 */
	public java.lang.Boolean getDistributeType() {
		return get("distribute_type");
	}

	/**
	 * 是否已过期
	 */
	public void setIsExpire(java.lang.Integer isExpire) {
		set("is_expire", isExpire);
	}
	
	/**
	 * 是否已过期
	 */
	public java.lang.Integer getIsExpire() {
		return getInt("is_expire");
	}

	/**
	 * 到期时间
	 */
	public void setExpireTime(java.lang.Integer expireTime) {
		set("expire_time", expireTime);
	}
	
	/**
	 * 到期时间
	 */
	public java.lang.Integer getExpireTime() {
		return getInt("expire_time");
	}

	/**
	 * 是否已完成
	 */
	public void setIsFinish(java.lang.Boolean isFinish) {
		set("is_finish", isFinish);
	}
	
	/**
	 * 是否已完成
	 */
	public java.lang.Boolean getIsFinish() {
		return get("is_finish");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 小程序form_id
	 */
	public void setFormId(java.lang.String formId) {
		set("form_id", formId);
	}
	
	/**
	 * 小程序form_id
	 */
	public java.lang.String getFormId() {
		return getStr("form_id");
	}

}
