package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrinterSetting<M extends BasePrinterSetting<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 打印机ID
	 */
	public void setPrinterId(java.lang.Integer printerId) {
		set("printer_id", printerId);
	}
	
	/**
	 * 打印机ID
	 */
	public java.lang.Integer getPrinterId() {
		return getInt("printer_id");
	}

	/**
	 * 打印模板ID
	 */
	public void setBlockId(java.lang.Integer blockId) {
		set("block_id", blockId);
	}
	
	/**
	 * 打印模板ID
	 */
	public java.lang.Integer getBlockId() {
		return getInt("block_id");
	}

	/**
	 * 打印方式 
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 打印方式 
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 是否打印规格 0--不打印 1--打印
	 */
	public void setIsAttr(java.lang.Integer isAttr) {
		set("is_attr", isAttr);
	}
	
	/**
	 * 是否打印规格 0--不打印 1--打印
	 */
	public java.lang.Integer getIsAttr() {
		return getInt("is_attr");
	}

}
