package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDistrict<M extends BaseDistrict<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setCitycode(java.lang.String citycode) {
		set("citycode", citycode);
	}
	
	public java.lang.String getCitycode() {
		return getStr("citycode");
	}

	public void setAdcode(java.lang.String adcode) {
		set("adcode", adcode);
	}
	
	public java.lang.String getAdcode() {
		return getStr("adcode");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 经度
	 */
	public void setLng(java.lang.String lng) {
		set("lng", lng);
	}
	
	/**
	 * 经度
	 */
	public java.lang.String getLng() {
		return getStr("lng");
	}

	/**
	 * 纬度
	 */
	public void setLat(java.lang.String lat) {
		set("lat", lat);
	}
	
	/**
	 * 纬度
	 */
	public java.lang.String getLat() {
		return getStr("lat");
	}

	public void setLevel(java.lang.String level) {
		set("level", level);
	}
	
	public java.lang.String getLevel() {
		return getStr("level");
	}

}
