package com.demo.common.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUploadConfig<M extends BaseUploadConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 存储类型：留空=本地，aliyun=阿里云oss，qcloud=腾讯云cos，qiniu=七牛云存储
	 */
	public void setStorageType(java.lang.String storageType) {
		set("storage_type", storageType);
	}
	
	/**
	 * 存储类型：留空=本地，aliyun=阿里云oss，qcloud=腾讯云cos，qiniu=七牛云存储
	 */
	public java.lang.String getStorageType() {
		return getStr("storage_type");
	}

	/**
	 * 阿里云oss配置，json格式
	 */
	public void setAliyun(java.lang.String aliyun) {
		set("aliyun", aliyun);
	}
	
	/**
	 * 阿里云oss配置，json格式
	 */
	public java.lang.String getAliyun() {
		return getStr("aliyun");
	}

	/**
	 * 腾讯云cos配置，json格式
	 */
	public void setQcloud(java.lang.String qcloud) {
		set("qcloud", qcloud);
	}
	
	/**
	 * 腾讯云cos配置，json格式
	 */
	public java.lang.String getQcloud() {
		return getStr("qcloud");
	}

	/**
	 * 七牛云存储配置，json格式
	 */
	public void setQiniu(java.lang.String qiniu) {
		set("qiniu", qiniu);
	}
	
	/**
	 * 七牛云存储配置，json格式
	 */
	public java.lang.String getQiniu() {
		return getStr("qiniu");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

}
