package com.demo.common.test;

import com.demo.common.test.BaseCouponAutoSend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponAutoSend extends BaseCouponAutoSend<CouponAutoSend> {
	
}
