package com.demo.common.test;

import com.demo.common.test.BaseDiyTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DiyTemplate extends BaseDiyTemplate<DiyTemplate> {
	
}
