package com.demo.common.test;

import com.demo.common.test.BaseFreeDeliveryRules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FreeDeliveryRules extends BaseFreeDeliveryRules<FreeDeliveryRules> {
	
}
