package com.demo.common.test;

import com.demo.common.test.BaseFxhbHongbao;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FxhbHongbao extends BaseFxhbHongbao<FxhbHongbao> {
	
}
