package com.demo.common.test;

import com.demo.common.test.BaseFxhbSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FxhbSetting extends BaseFxhbSetting<FxhbSetting> {
	
}
