package com.demo.common.test;

import com.demo.common.test.BaseGoodsShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsShare extends BaseGoodsShare<GoodsShare> {
	
}
