package com.demo.common.test;

import com.demo.common.test.BaseGwdBuyList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GwdBuyList extends BaseGwdBuyList<GwdBuyList> {
	
}
