package com.demo.common.test;

import com.demo.common.test.BaseGwdLikeList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GwdLikeList extends BaseGwdLikeList<GwdLikeList> {
	
}
