package com.demo.common.test;

import com.demo.common.test.BaseGwdLikeUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GwdLikeUser extends BaseGwdLikeUser<GwdLikeUser> {
	
}
