package com.demo.common.test;

import com.demo.common.test.BaseGwdSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GwdSetting extends BaseGwdSetting<GwdSetting> {
	
}
