package com.demo.common.test;

import com.demo.common.test.BaseInOrderComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InOrderComment extends BaseInOrderComment<InOrderComment> {
	
}
