package com.demo.common.test;

import com.demo.common.test.BaseIntegralOrderDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralOrderDetail extends BaseIntegralOrderDetail<IntegralOrderDetail> {
	
}
