package com.demo.common.test;

import com.demo.common.test.BaseIntegralCat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralCat extends BaseIntegralCat<IntegralCat> {
	
}
