package com.demo.common.test;

import com.demo.common.test.BaseIntegralGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralGoods extends BaseIntegralGoods<IntegralGoods> {
	
}
