package com.demo.common.test;

import com.demo.common.test.BaseIntegralSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralSetting extends BaseIntegralSetting<IntegralSetting> {
	
}
