package com.demo.common.test;

import com.demo.common.test.BaseIntegralLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralLog extends BaseIntegralLog<IntegralLog> {
	
}
