package com.demo.common.test;

import com.demo.common.test.BaseIntegralOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralOrder extends BaseIntegralOrder<IntegralOrder> {
	
}
