package com.demo.common.test;

import com.demo.common.test.BaseIntegralCouponOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralCouponOrder extends BaseIntegralCouponOrder<IntegralCouponOrder> {
	
}
