package com.demo.common.test;

import com.demo.common.test.BaseLevelOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LevelOrder extends BaseLevelOrder<LevelOrder> {
	
}
