package com.demo.common.test;

import com.demo.common.test.BaseLotteryReserve;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryReserve extends BaseLotteryReserve<LotteryReserve> {
	
}
