package com.demo.common.test;

import com.demo.common.test.BaseLotteryGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryGoods extends BaseLotteryGoods<LotteryGoods> {
	
}
