package com.demo.common.test;

import com.demo.common.test.BaseLotteryLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryLog extends BaseLotteryLog<LotteryLog> {
	
}
