package com.demo.common.test;

import com.demo.common.test.BaseLotterySetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotterySetting extends BaseLotterySetting<LotterySetting> {
	
}
