package com.demo.common.test;

import com.demo.common.test.BaseMailSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MailSetting extends BaseMailSetting<MailSetting> {
	
}
