package com.demo.common.test;

import com.demo.common.test.BaseMchAccountLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MchAccountLog extends BaseMchAccountLog<MchAccountLog> {
	
}
