package com.demo.common.test;

import com.demo.common.test.BaseMchCommonCat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MchCommonCat extends BaseMchCommonCat<MchCommonCat> {
	
}
