package com.demo.common.test;

import com.demo.common.test.BaseMchGoodsCat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MchGoodsCat extends BaseMchGoodsCat<MchGoodsCat> {
	
}
