package com.demo.common.test;

import com.demo.common.test.BaseMchPostageRules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MchPostageRules extends BaseMchPostageRules<MchPostageRules> {
	
}
