package com.demo.common.test;

import com.demo.common.test.BaseMchSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MchSetting extends BaseMchSetting<MchSetting> {
	
}
