package com.demo.common.test;

import com.demo.common.test.BaseMchVisitLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MchVisitLog extends BaseMchVisitLog<MchVisitLog> {
	
}
