package com.demo.common.test;

import com.demo.common.test.BaseMiaoshaGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MiaoshaGoods extends BaseMiaoshaGoods<MiaoshaGoods> {
	
}
