package com.demo.common.test;

import com.demo.common.test.BaseMsGoodsPic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsGoodsPic extends BaseMsGoodsPic<MsGoodsPic> {
	
}
