package com.demo.common.test;

import com.demo.common.test.BaseMsOrderComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsOrderComment extends BaseMsOrderComment<MsOrderComment> {
	
}
