package com.demo.common.test;

import com.demo.common.test.BaseMsOrderRefund;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsOrderRefund extends BaseMsOrderRefund<MsOrderRefund> {
	
}
