package com.demo.common.test;

import com.demo.common.test.BaseOrderShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderShare extends BaseOrderShare<OrderShare> {
	
}
