package com.demo.common.test;

import com.demo.common.test.BaseOrderDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDetail extends BaseOrderDetail<OrderDetail> {
	
}
