package com.demo.common.test;

import com.demo.common.test.BaseOrderExpress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderExpress extends BaseOrderExpress<OrderExpress> {
	
}
