package com.demo.common.test;

import com.demo.common.test.BaseOrderMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderMessage extends BaseOrderMessage<OrderMessage> {
	
}
