package com.demo.common.test;

import com.demo.common.test.BaseOrderUnion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderUnion extends BaseOrderUnion<OrderUnion> {
	
}
