package com.demo.common.test;

import com.demo.common.test.BaseOrderComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderComment extends BaseOrderComment<OrderComment> {
	
}
