package com.demo.common.test;

import com.demo.common.test.BasePondSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PondSetting extends BasePondSetting<PondSetting> {
	
}
