package com.demo.common.test;

import com.demo.common.test.BasePostageRules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostageRules extends BasePostageRules<PostageRules> {
	
}
