package com.demo.common.test;

import com.demo.common.test.BasePrinterSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrinterSetting extends BasePrinterSetting<PrinterSetting> {
	
}
