package com.demo.common.test;

import com.demo.common.test.BasePtGoodsDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtGoodsDetail extends BasePtGoodsDetail<PtGoodsDetail> {
	
}
