package com.demo.common.test;

import com.demo.common.test.BasePtGoodsPic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtGoodsPic extends BasePtGoodsPic<PtGoodsPic> {
	
}
