package com.demo.common.test;

import com.demo.common.test.BasePtOrderRefund;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtOrderRefund extends BasePtOrderRefund<PtOrderRefund> {
	
}
