package com.demo.common.test;

import com.demo.common.test.BasePtOrderComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtOrderComment extends BasePtOrderComment<PtOrderComment> {
	
}
