package com.demo.common.test;

import com.demo.common.test.BasePtOrderDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtOrderDetail extends BasePtOrderDetail<PtOrderDetail> {
	
}
