package com.demo.common.test;

import com.demo.common.test.BaseRefundAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RefundAddress extends BaseRefundAddress<RefundAddress> {
	
}
