package com.demo.common.test;

import com.demo.common.test.BaseScratchLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScratchLog extends BaseScratchLog<ScratchLog> {
	
}
