package com.demo.common.test;

import com.demo.common.test.BaseScratchSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScratchSetting extends BaseScratchSetting<ScratchSetting> {
	
}
