package com.demo.common.test;

import com.demo.common.test.BaseSmsSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsSetting extends BaseSmsSetting<SmsSetting> {
	
}
