package com.demo.common.test;

import com.demo.common.test.BaseStepRemind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StepRemind extends BaseStepRemind<StepRemind> {
	
}
