package com.demo.common.test;

import com.demo.common.test.BaseStepSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StepSetting extends BaseStepSetting<StepSetting> {
	
}
