package com.demo.common.test;

import com.demo.common.test.BaseStepActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StepActivity extends BaseStepActivity<StepActivity> {
	
}
