package com.demo.common.test;

import com.demo.common.test.BaseTemplateMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TemplateMsg extends BaseTemplateMsg<TemplateMsg> {
	
}
