package com.demo.common.test;

import com.demo.common.test.BaseTerritorialLimitation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TerritorialLimitation extends BaseTerritorialLimitation<TerritorialLimitation> {
	
}
