package com.demo.common.test;

import com.demo.common.test.BaseTopicFavorite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TopicFavorite extends BaseTopicFavorite<TopicFavorite> {
	
}
