package com.demo.common.test;

import com.demo.common.test.BaseUploadConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadConfig extends BaseUploadConfig<UploadConfig> {
	
}
