package com.demo.common.test;

import com.demo.common.test.BaseUploadFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadFile extends BaseUploadFile<UploadFile> {
	
}
