package com.demo.common.test;

import com.demo.common.test.BaseUserAuthLogin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAuthLogin extends BaseUserAuthLogin<UserAuthLogin> {
	
}
