package com.demo.common.test;

import com.demo.common.test.BaseUserCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCoupon extends BaseUserCoupon<UserCoupon> {
	
}
