package com.demo.common.test;

import com.demo.common.test.BaseUserShareMoney;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserShareMoney extends BaseUserShareMoney<UserShareMoney> {
	
}
