package com.demo.common.test;

import com.demo.common.test.BaseUserAccountLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAccountLog extends BaseUserAccountLog<UserAccountLog> {
	
}
