package com.demo.common.test;

import com.demo.common.test.BaseUserFormId;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFormId extends BaseUserFormId<UserFormId> {
	
}
