package com.demo.common.test;

import com.demo.common.test.BaseWe7UserAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class We7UserAuth extends BaseWe7UserAuth<We7UserAuth> {
	
}
