package com.demo.common.test;

import com.demo.common.test.BaseWechatTemplateMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatTemplateMessage extends BaseWechatTemplateMessage<WechatTemplateMessage> {
	
}
