package com.demo.common.test;

import com.demo.common.test.BaseWechatPlatform;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatPlatform extends BaseWechatPlatform<WechatPlatform> {
	
}
