package com.demo.common.test;

import com.demo.common.test.BaseYyGoodsPic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YyGoodsPic extends BaseYyGoodsPic<YyGoodsPic> {
	
}
