package com.demo.common.test;

import com.demo.common.test.BaseYyOrderComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YyOrderComment extends BaseYyOrderComment<YyOrderComment> {
	
}
