package com.demo.common.test;

import com.demo.common.test.BaseYyOrderForm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YyOrderForm extends BaseYyOrderForm<YyOrderForm> {
	
}
