package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}
	
	/**
	 * 订单号
	 */
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 订单总费用(包含运费）
	 */
	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
	}
	
	/**
	 * 订单总费用(包含运费）
	 */
	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	/**
	 * 实际支付总费用(含运费）
	 */
	public void setPayPrice(java.math.BigDecimal payPrice) {
		set("pay_price", payPrice);
	}
	
	/**
	 * 实际支付总费用(含运费）
	 */
	public java.math.BigDecimal getPayPrice() {
		return get("pay_price");
	}

	/**
	 * 运费
	 */
	public void setExpressPrice(java.math.BigDecimal expressPrice) {
		set("express_price", expressPrice);
	}
	
	/**
	 * 运费
	 */
	public java.math.BigDecimal getExpressPrice() {
		return get("express_price");
	}

	/**
	 * 收货人姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 收货人姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 收货人手机
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 收货人手机
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 收货地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 收货地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 订单备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 订单备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 支付状态：0=未支付，1=已支付
	 */
	public void setIsPay(java.lang.Integer isPay) {
		set("is_pay", isPay);
	}
	
	/**
	 * 支付状态：0=未支付，1=已支付
	 */
	public java.lang.Integer getIsPay() {
		return getInt("is_pay");
	}

	/**
	 * 支付方式：1=微信支付
	 */
	public void setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
	}
	
	/**
	 * 支付方式：1=微信支付
	 */
	public java.lang.Integer getPayType() {
		return getInt("pay_type");
	}

	/**
	 * 支付时间
	 */
	public void setPayTime(java.lang.Integer payTime) {
		set("pay_time", payTime);
	}
	
	/**
	 * 支付时间
	 */
	public java.lang.Integer getPayTime() {
		return getInt("pay_time");
	}

	/**
	 * 发货状态：0=未发货，1=已发货
	 */
	public void setIsSend(java.lang.Integer isSend) {
		set("is_send", isSend);
	}
	
	/**
	 * 发货状态：0=未发货，1=已发货
	 */
	public java.lang.Integer getIsSend() {
		return getInt("is_send");
	}

	/**
	 * 发货时间
	 */
	public void setSendTime(java.lang.Integer sendTime) {
		set("send_time", sendTime);
	}
	
	/**
	 * 发货时间
	 */
	public java.lang.Integer getSendTime() {
		return getInt("send_time");
	}

	/**
	 * 物流公司
	 */
	public void setExpress(java.lang.String express) {
		set("express", express);
	}
	
	/**
	 * 物流公司
	 */
	public java.lang.String getExpress() {
		return getStr("express");
	}

	public void setExpressNo(java.lang.String expressNo) {
		set("express_no", expressNo);
	}
	
	public java.lang.String getExpressNo() {
		return getStr("express_no");
	}

	/**
	 * 确认收货状态：0=未确认，1=已确认收货
	 */
	public void setIsConfirm(java.lang.Integer isConfirm) {
		set("is_confirm", isConfirm);
	}
	
	/**
	 * 确认收货状态：0=未确认，1=已确认收货
	 */
	public java.lang.Integer getIsConfirm() {
		return getInt("is_confirm");
	}

	/**
	 * 确认收货时间
	 */
	public void setConfirmTime(java.lang.Integer confirmTime) {
		set("confirm_time", confirmTime);
	}
	
	/**
	 * 确认收货时间
	 */
	public java.lang.Integer getConfirmTime() {
		return getInt("confirm_time");
	}

	/**
	 * 是否已评价：0=未评价，1=已评价
	 */
	public void setIsComment(java.lang.Integer isComment) {
		set("is_comment", isComment);
	}
	
	/**
	 * 是否已评价：0=未评价，1=已评价
	 */
	public java.lang.Integer getIsComment() {
		return getInt("is_comment");
	}

	/**
	 * 是否申请取消订单：0=否，1=申请取消订单
	 */
	public void setApplyDelete(java.lang.Integer applyDelete) {
		set("apply_delete", applyDelete);
	}
	
	/**
	 * 是否申请取消订单：0=否，1=申请取消订单
	 */
	public java.lang.Integer getApplyDelete() {
		return getInt("apply_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 是否发放佣金
	 */
	public void setIsPrice(java.lang.Integer isPrice) {
		set("is_price", isPrice);
	}
	
	/**
	 * 是否发放佣金
	 */
	public java.lang.Integer getIsPrice() {
		return getInt("is_price");
	}

	/**
	 * 用户上级ID
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 用户上级ID
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 一级佣金
	 */
	public void setFirstPrice(java.math.BigDecimal firstPrice) {
		set("first_price", firstPrice);
	}
	
	/**
	 * 一级佣金
	 */
	public java.math.BigDecimal getFirstPrice() {
		return get("first_price");
	}

	/**
	 * 二级佣金
	 */
	public void setSecondPrice(java.math.BigDecimal secondPrice) {
		set("second_price", secondPrice);
	}
	
	/**
	 * 二级佣金
	 */
	public java.math.BigDecimal getSecondPrice() {
		return get("second_price");
	}

	/**
	 * 三级佣金
	 */
	public void setThirdPrice(java.math.BigDecimal thirdPrice) {
		set("third_price", thirdPrice);
	}
	
	/**
	 * 三级佣金
	 */
	public java.math.BigDecimal getThirdPrice() {
		return get("third_price");
	}

	/**
	 * 优惠券抵消金额
	 */
	public void setCouponSubPrice(java.math.BigDecimal couponSubPrice) {
		set("coupon_sub_price", couponSubPrice);
	}
	
	/**
	 * 优惠券抵消金额
	 */
	public java.math.BigDecimal getCouponSubPrice() {
		return get("coupon_sub_price");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 是否到店自提 0--否 1--是
	 */
	public void setIsOffline(java.lang.Integer isOffline) {
		set("is_offline", isOffline);
	}
	
	/**
	 * 是否到店自提 0--否 1--是
	 */
	public java.lang.Integer getIsOffline() {
		return getInt("is_offline");
	}

	/**
	 * 核销员user_id
	 */
	public void setClerkId(java.lang.Integer clerkId) {
		set("clerk_id", clerkId);
	}
	
	/**
	 * 核销员user_id
	 */
	public java.lang.Integer getClerkId() {
		return getInt("clerk_id");
	}

	/**
	 * 收货地址信息，json格式
	 */
	public void setAddressData(java.lang.String addressData) {
		set("address_data", addressData);
	}
	
	/**
	 * 收货地址信息，json格式
	 */
	public java.lang.String getAddressData() {
		return getStr("address_data");
	}

	/**
	 * 是否取消
	 */
	public void setIsCancel(java.lang.Integer isCancel) {
		set("is_cancel", isCancel);
	}
	
	/**
	 * 是否取消
	 */
	public java.lang.Integer getIsCancel() {
		return getInt("is_cancel");
	}

	/**
	 * 核销码
	 */
	public void setOfflineQrcode(java.lang.String offlineQrcode) {
		set("offline_qrcode", offlineQrcode);
	}
	
	/**
	 * 核销码
	 */
	public java.lang.String getOfflineQrcode() {
		return getStr("offline_qrcode");
	}

	/**
	 * 修改前的价格
	 */
	public void setBeforeUpdatePrice(java.math.BigDecimal beforeUpdatePrice) {
		set("before_update_price", beforeUpdatePrice);
	}
	
	/**
	 * 修改前的价格
	 */
	public java.math.BigDecimal getBeforeUpdatePrice() {
		return get("before_update_price");
	}

	/**
	 * 自提门店ID
	 */
	public void setShopId(java.lang.Integer shopId) {
		set("shop_id", shopId);
	}
	
	/**
	 * 自提门店ID
	 */
	public java.lang.Integer getShopId() {
		return getInt("shop_id");
	}

	/**
	 * 会员折扣
	 */
	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	/**
	 * 会员折扣
	 */
	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	/**
	 * 使用的优惠券ID
	 */
	public void setUserCouponId(java.lang.Integer userCouponId) {
		set("user_coupon_id", userCouponId);
	}
	
	/**
	 * 使用的优惠券ID
	 */
	public java.lang.Integer getUserCouponId() {
		return getInt("user_coupon_id");
	}

	/**
	 * 积分使用
	 */
	public void setIntegral(java.lang.String integral) {
		set("integral", integral);
	}
	
	/**
	 * 积分使用
	 */
	public java.lang.String getIntegral() {
		return getStr("integral");
	}

	/**
	 * 是否发放积分【1=> 已发放 ， 0=> 未发放】
	 */
	public void setGiveIntegral(java.lang.Integer giveIntegral) {
		set("give_integral", giveIntegral);
	}
	
	/**
	 * 是否发放积分【1=> 已发放 ， 0=> 未发放】
	 */
	public java.lang.Integer getGiveIntegral() {
		return getInt("give_integral");
	}

	/**
	 * 用户上二级ID
	 */
	public void setParentId1(java.lang.Integer parentId1) {
		set("parent_id_1", parentId1);
	}
	
	/**
	 * 用户上二级ID
	 */
	public java.lang.Integer getParentId1() {
		return getInt("parent_id_1");
	}

	/**
	 * 用户上三级ID
	 */
	public void setParentId2(java.lang.Integer parentId2) {
		set("parent_id_2", parentId2);
	}
	
	/**
	 * 用户上三级ID
	 */
	public java.lang.Integer getParentId2() {
		return getInt("parent_id_2");
	}

	/**
	 * 是否超过售后时间
	 */
	public void setIsSale(java.lang.Integer isSale) {
		set("is_sale", isSale);
	}
	
	/**
	 * 是否超过售后时间
	 */
	public java.lang.Integer getIsSale() {
		return getInt("is_sale");
	}

	/**
	 * 商家留言
	 */
	public void setWords(java.lang.String words) {
		set("words", words);
	}
	
	/**
	 * 商家留言
	 */
	public java.lang.String getWords() {
		return getStr("words");
	}

	/**
	 * 版本
	 */
	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	/**
	 * 版本
	 */
	public java.lang.String getVersion() {
		return getStr("version");
	}

	/**
	 * 减免的运费
	 */
	public void setExpressPrice1(java.math.BigDecimal expressPrice1) {
		set("express_price_1", expressPrice1);
	}
	
	/**
	 * 减免的运费
	 */
	public java.math.BigDecimal getExpressPrice1() {
		return get("express_price_1");
	}

	public void setIsRecycle(java.lang.Integer isRecycle) {
		set("is_recycle", isRecycle);
	}
	
	public java.lang.Integer getIsRecycle() {
		return getInt("is_recycle");
	}

	/**
	 * 自购返利
	 */
	public void setRebate(java.math.BigDecimal rebate) {
		set("rebate", rebate);
	}
	
	/**
	 * 自购返利
	 */
	public java.math.BigDecimal getRebate() {
		return get("rebate");
	}

	/**
	 * 价格修改前的运费
	 */
	public void setBeforeUpdateExpress(java.math.BigDecimal beforeUpdateExpress) {
		set("before_update_express", beforeUpdateExpress);
	}
	
	/**
	 * 价格修改前的运费
	 */
	public java.math.BigDecimal getBeforeUpdateExpress() {
		return get("before_update_express");
	}

	/**
	 * 商家备注
	 */
	public void setSellerComments(java.lang.String sellerComments) {
		set("seller_comments", sellerComments);
	}
	
	/**
	 * 商家备注
	 */
	public java.lang.String getSellerComments() {
		return getStr("seller_comments");
	}

	/**
	 * 入驻商户id
	 */
	public void setMchId(java.lang.Integer mchId) {
		set("mch_id", mchId);
	}
	
	/**
	 * 入驻商户id
	 */
	public java.lang.Integer getMchId() {
		return getInt("mch_id");
	}

	/**
	 * 合并订单的id
	 */
	public void setOrderUnionId(java.lang.Integer orderUnionId) {
		set("order_union_id", orderUnionId);
	}
	
	/**
	 * 合并订单的id
	 */
	public java.lang.Integer getOrderUnionId() {
		return getInt("order_union_id");
	}

	/**
	 * 是否已转入商户账户：0=否，1=是
	 */
	public void setIsTransfer(java.lang.Integer isTransfer) {
		set("is_transfer", isTransfer);
	}
	
	/**
	 * 是否已转入商户账户：0=否，1=是
	 */
	public java.lang.Integer getIsTransfer() {
		return getInt("is_transfer");
	}

	/**
	 * 0:普通订单 1大转盘订单
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 0:普通订单 1大转盘订单
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 发放佣金的金额
	 */
	public void setSharePrice(java.math.BigDecimal sharePrice) {
		set("share_price", sharePrice);
	}
	
	/**
	 * 发放佣金的金额
	 */
	public java.math.BigDecimal getSharePrice() {
		return get("share_price");
	}

	/**
	 * 是否显示 0--不显示 1--显示
	 */
	public void setIsShow(java.lang.Integer isShow) {
		set("is_show", isShow);
	}
	
	/**
	 * 是否显示 0--不显示 1--显示
	 */
	public java.lang.Integer getIsShow() {
		return getInt("is_show");
	}

	/**
	 * 货币：活力币
	 */
	public void setCurrency(java.math.BigDecimal currency) {
		set("currency", currency);
	}
	
	/**
	 * 货币：活力币
	 */
	public java.math.BigDecimal getCurrency() {
		return get("currency");
	}

}
