package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStepLog<M extends BaseStepLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * stepID
	 */
	public void setStepId(java.lang.Integer stepId) {
		set("step_id", stepId);
	}
	
	/**
	 * stepID
	 */
	public java.lang.Integer getStepId() {
		return getInt("step_id");
	}

	/**
	 * 兑换布数
	 */
	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	/**
	 * 兑换布数
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 1收入 2支出 
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 1收入 2支出 
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 0 布数兑换 1商品兑换 2 布数挑战
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 0 布数兑换 1商品兑换 2 布数挑战
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 活力币
	 */
	public void setStepCurrency(java.math.BigDecimal stepCurrency) {
		set("step_currency", stepCurrency);
	}
	
	/**
	 * 活力币
	 */
	public java.math.BigDecimal getStepCurrency() {
		return get("step_currency");
	}

	/**
	 * 订单/活动
	 */
	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	/**
	 * 订单/活动
	 */
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	/**
	 * 领取时间
	 */
	public void setRaffleTime(java.lang.Integer raffleTime) {
		set("raffle_time", raffleTime);
	}
	
	/**
	 * 领取时间
	 */
	public java.lang.Integer getRaffleTime() {
		return getInt("raffle_time");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}

}
