package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsSetting<M extends BaseMsSetting<M>> extends Model<M> implements IBean {

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

	/**
	 * 未付款自动取消时间
	 */
	public void setUnpaid(java.lang.Long unpaid) {
		set("unpaid", unpaid);
	}
	
	/**
	 * 未付款自动取消时间
	 */
	public java.lang.Long getUnpaid() {
		return getLong("unpaid");
	}

	/**
	 * 是否开启分销 0--关闭 1--开启
	 */
	public void setIsShare(java.lang.Integer isShare) {
		set("is_share", isShare);
	}
	
	/**
	 * 是否开启分销 0--关闭 1--开启
	 */
	public java.lang.Integer getIsShare() {
		return getInt("is_share");
	}

	/**
	 * 是否开启短信通知
	 */
	public void setIsSms(java.lang.Integer isSms) {
		set("is_sms", isSms);
	}
	
	/**
	 * 是否开启短信通知
	 */
	public java.lang.Integer getIsSms() {
		return getInt("is_sms");
	}

	/**
	 * 是否开启订单打印
	 */
	public void setIsPrint(java.lang.Integer isPrint) {
		set("is_print", isPrint);
	}
	
	/**
	 * 是否开启订单打印
	 */
	public java.lang.Integer getIsPrint() {
		return getInt("is_print");
	}

	/**
	 * 是否开启邮件通知
	 */
	public void setIsMail(java.lang.Integer isMail) {
		set("is_mail", isMail);
	}
	
	/**
	 * 是否开启邮件通知
	 */
	public java.lang.Integer getIsMail() {
		return getInt("is_mail");
	}

	/**
	 * 区域限制  1-开启 0-关闭
	 */
	public void setIsArea(java.lang.Boolean isArea) {
		set("is_area", isArea);
	}
	
	/**
	 * 区域限制  1-开启 0-关闭
	 */
	public java.lang.Boolean getIsArea() {
		return get("is_area");
	}

}
