package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMchPostageRules<M extends BaseMchPostageRules<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMchId(java.lang.Integer mchId) {
		set("mch_id", mchId);
	}
	
	public java.lang.Integer getMchId() {
		return getInt("mch_id");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 物流公司
	 */
	public void setExpressId(java.lang.Integer expressId) {
		set("express_id", expressId);
	}
	
	/**
	 * 物流公司
	 */
	public java.lang.Integer getExpressId() {
		return getInt("express_id");
	}

	/**
	 * 规则详细
	 */
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	/**
	 * 规则详细
	 */
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 是否启用：0=否，1=是
	 */
	public void setIsEnable(java.lang.Integer isEnable) {
		set("is_enable", isEnable);
	}
	
	/**
	 * 是否启用：0=否，1=是
	 */
	public java.lang.Integer getIsEnable() {
		return getInt("is_enable");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 快递公司
	 */
	public void setExpress(java.lang.String express) {
		set("express", express);
	}
	
	/**
	 * 快递公司
	 */
	public java.lang.String getExpress() {
		return getStr("express");
	}

	/**
	 * 计费方式【1=>按重计费、2=>按件计费】
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 计费方式【1=>按重计费、2=>按件计费】
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
