package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHomeNav<M extends BaseHomeNav<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 图标名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 图标名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 打开方式
	 */
	public void setOpenType(java.lang.String openType) {
		set("open_type", openType);
	}
	
	/**
	 * 打开方式
	 */
	public java.lang.String getOpenType() {
		return getStr("open_type");
	}

	public void setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
	}
	
	public java.lang.String getPicUrl() {
		return getStr("pic_url");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 排序，升序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序，升序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 是否隐藏 0 显示 1隐藏 
	 */
	public void setIsHide(java.lang.Integer isHide) {
		set("is_hide", isHide);
	}
	
	/**
	 * 是否隐藏 0 显示 1隐藏 
	 */
	public java.lang.Integer getIsHide() {
		return getInt("is_hide");
	}

}
