package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttr<M extends BaseAttr<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAttrGroupId(java.lang.Integer attrGroupId) {
		set("attr_group_id", attrGroupId);
	}
	
	public java.lang.Integer getAttrGroupId() {
		return getInt("attr_group_id");
	}

	public void setAttrName(java.lang.String attrName) {
		set("attr_name", attrName);
	}
	
	public java.lang.String getAttrName() {
		return getStr("attr_name");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 是否是默认属性
	 */
	public void setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
	}
	
	/**
	 * 是否是默认属性
	 */
	public java.lang.Integer getIsDefault() {
		return getInt("is_default");
	}

}
