package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderShare<M extends BaseOrderShare<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 类型 0--拼团 1--预约
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 类型 0--拼团 1--预约
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 订单id
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	/**
	 * 订单id
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 一级分销商id
	 */
	public void setParentId1(java.lang.Integer parentId1) {
		set("parent_id_1", parentId1);
	}
	
	/**
	 * 一级分销商id
	 */
	public java.lang.Integer getParentId1() {
		return getInt("parent_id_1");
	}

	/**
	 * 二级分销商id
	 */
	public void setParentId2(java.lang.Integer parentId2) {
		set("parent_id_2", parentId2);
	}
	
	/**
	 * 二级分销商id
	 */
	public java.lang.Integer getParentId2() {
		return getInt("parent_id_2");
	}

	/**
	 * 三级分销商id
	 */
	public void setParentId3(java.lang.Integer parentId3) {
		set("parent_id_3", parentId3);
	}
	
	/**
	 * 三级分销商id
	 */
	public java.lang.Integer getParentId3() {
		return getInt("parent_id_3");
	}

	/**
	 * 一级分销佣金
	 */
	public void setFirstPrice(java.math.BigDecimal firstPrice) {
		set("first_price", firstPrice);
	}
	
	/**
	 * 一级分销佣金
	 */
	public java.math.BigDecimal getFirstPrice() {
		return get("first_price");
	}

	/**
	 * 二级分销佣金
	 */
	public void setSecondPrice(java.math.BigDecimal secondPrice) {
		set("second_price", secondPrice);
	}
	
	/**
	 * 二级分销佣金
	 */
	public java.math.BigDecimal getSecondPrice() {
		return get("second_price");
	}

	/**
	 * 三级分销佣金
	 */
	public void setThirdPrice(java.math.BigDecimal thirdPrice) {
		set("third_price", thirdPrice);
	}
	
	/**
	 * 三级分销佣金
	 */
	public java.math.BigDecimal getThirdPrice() {
		return get("third_price");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	public java.lang.String getVersion() {
		return getStr("version");
	}

	/**
	 * 自购返利
	 */
	public void setRebate(java.math.BigDecimal rebate) {
		set("rebate", rebate);
	}
	
	/**
	 * 自购返利
	 */
	public java.math.BigDecimal getRebate() {
		return get("rebate");
	}

	/**
	 * 下单用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 下单用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

}
