package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMchSetting<M extends BaseMchSetting<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMchId(java.lang.Integer mchId) {
		set("mch_id", mchId);
	}
	
	public java.lang.Integer getMchId() {
		return getInt("mch_id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 是否开启分销 0--不开启 1--开启
	 */
	public void setIsShare(java.lang.Integer isShare) {
		set("is_share", isShare);
	}
	
	/**
	 * 是否开启分销 0--不开启 1--开启
	 */
	public java.lang.Integer getIsShare() {
		return getInt("is_share");
	}

}
