package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthRole<M extends BaseAuthRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setCreatedAt(java.lang.Integer createdAt) {
		set("created_at", createdAt);
	}
	
	public java.lang.Integer getCreatedAt() {
		return getInt("created_at");
	}

	public void setUpdatedAt(java.lang.Integer updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.lang.Integer getUpdatedAt() {
		return getInt("updated_at");
	}

	/**
	 * 创建者ID
	 */
	public void setCreatorId(java.lang.Integer creatorId) {
		set("creator_id", creatorId);
	}
	
	/**
	 * 创建者ID
	 */
	public java.lang.Integer getCreatorId() {
		return getInt("creator_id");
	}

}
