package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCard<M extends BaseUserCard<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 卡券ID
	 */
	public void setCardId(java.lang.Integer cardId) {
		set("card_id", cardId);
	}
	
	/**
	 * 卡券ID
	 */
	public java.lang.Integer getCardId() {
		return getInt("card_id");
	}

	/**
	 * 卡券名称
	 */
	public void setCardName(java.lang.String cardName) {
		set("card_name", cardName);
	}
	
	/**
	 * 卡券名称
	 */
	public java.lang.String getCardName() {
		return getStr("card_name");
	}

	public void setCardPicUrl(java.lang.String cardPicUrl) {
		set("card_pic_url", cardPicUrl);
	}
	
	public java.lang.String getCardPicUrl() {
		return getStr("card_pic_url");
	}

	/**
	 * 卡券描述
	 */
	public void setCardContent(java.lang.String cardContent) {
		set("card_content", cardContent);
	}
	
	/**
	 * 卡券描述
	 */
	public java.lang.String getCardContent() {
		return getStr("card_content");
	}

	/**
	 * 是否使用 0--未使用 1--已使用
	 */
	public void setIsUse(java.lang.Integer isUse) {
		set("is_use", isUse);
	}
	
	/**
	 * 是否使用 0--未使用 1--已使用
	 */
	public java.lang.Integer getIsUse() {
		return getInt("is_use");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 核销人id
	 */
	public void setClerkId(java.lang.Integer clerkId) {
		set("clerk_id", clerkId);
	}
	
	/**
	 * 核销人id
	 */
	public java.lang.Integer getClerkId() {
		return getInt("clerk_id");
	}

	/**
	 * 店铺ID
	 */
	public void setShopId(java.lang.Integer shopId) {
		set("shop_id", shopId);
	}
	
	/**
	 * 店铺ID
	 */
	public java.lang.Integer getShopId() {
		return getInt("shop_id");
	}

	/**
	 *  核销时间
	 */
	public void setClerkTime(java.lang.Integer clerkTime) {
		set("clerk_time", clerkTime);
	}
	
	/**
	 *  核销时间
	 */
	public java.lang.Integer getClerkTime() {
		return getInt("clerk_time");
	}

	/**
	 * 发放卡券的订单id
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	/**
	 * 发放卡券的订单id
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 商品ID
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	/**
	 * 商品ID
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

}
