package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYySetting<M extends BaseYySetting<M>> extends Model<M> implements IBean {

	/**
	 * 是否显示分类
	 */
	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}
	
	/**
	 * 是否显示分类
	 */
	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

	/**
	 * 参数
	 */
	public void setCat(java.lang.Integer cat) {
		set("cat", cat);
	}
	
	/**
	 * 参数
	 */
	public java.lang.Integer getCat() {
		return getInt("cat");
	}

	/**
	 * 预约成功模板通知
	 */
	public void setSuccessNotice(java.lang.String successNotice) {
		set("success_notice", successNotice);
	}
	
	/**
	 * 预约成功模板通知
	 */
	public java.lang.String getSuccessNotice() {
		return getStr("success_notice");
	}

	/**
	 * 退款模板id
	 */
	public void setRefundNotice(java.lang.String refundNotice) {
		set("refund_notice", refundNotice);
	}
	
	/**
	 * 退款模板id
	 */
	public java.lang.String getRefundNotice() {
		return getStr("refund_notice");
	}

	/**
	 * 是否开启分销 0--关闭 1--开启
	 */
	public void setIsShare(java.lang.Integer isShare) {
		set("is_share", isShare);
	}
	
	/**
	 * 是否开启分销 0--关闭 1--开启
	 */
	public java.lang.Integer getIsShare() {
		return getInt("is_share");
	}

	/**
	 * 是否开启短信通知
	 */
	public void setIsSms(java.lang.Integer isSms) {
		set("is_sms", isSms);
	}
	
	/**
	 * 是否开启短信通知
	 */
	public java.lang.Integer getIsSms() {
		return getInt("is_sms");
	}

	/**
	 * 是否开启订单打印
	 */
	public void setIsPrint(java.lang.Integer isPrint) {
		set("is_print", isPrint);
	}
	
	/**
	 * 是否开启订单打印
	 */
	public java.lang.Integer getIsPrint() {
		return getInt("is_print");
	}

	/**
	 * 是否开启邮件通知
	 */
	public void setIsMail(java.lang.Integer isMail) {
		set("is_mail", isMail);
	}
	
	/**
	 * 是否开启邮件通知
	 */
	public java.lang.Integer getIsMail() {
		return getInt("is_mail");
	}

}
