package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntegralSetting<M extends BaseIntegralSetting<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 积分说明
	 */
	public void setIntegralShuoming(java.lang.String integralShuoming) {
		set("integral_shuoming", integralShuoming);
	}
	
	/**
	 * 积分说明
	 */
	public java.lang.String getIntegralShuoming() {
		return getStr("integral_shuoming");
	}

	/**
	 * 签到规则
	 */
	public void setRegisterRule(java.lang.String registerRule) {
		set("register_rule", registerRule);
	}
	
	/**
	 * 签到规则
	 */
	public java.lang.String getRegisterRule() {
		return getStr("register_rule");
	}

	/**
	 * 每日签到获得分数
	 */
	public void setRegisterIntegral(java.lang.Integer registerIntegral) {
		set("register_integral", registerIntegral);
	}
	
	/**
	 * 每日签到获得分数
	 */
	public java.lang.Integer getRegisterIntegral() {
		return getInt("register_integral");
	}

	/**
	 * 连续签到天数
	 */
	public void setRegisterContinuation(java.lang.Integer registerContinuation) {
		set("register_continuation", registerContinuation);
	}
	
	/**
	 * 连续签到天数
	 */
	public java.lang.Integer getRegisterContinuation() {
		return getInt("register_continuation");
	}

	/**
	 * 连续签到奖励
	 */
	public void setRegisterReward(java.lang.String registerReward) {
		set("register_reward", registerReward);
	}
	
	/**
	 * 连续签到奖励
	 */
	public java.lang.String getRegisterReward() {
		return getStr("register_reward");
	}

}
