package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderForm<M extends BaseOrderForm<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 表单key
	 */
	public void setKey(java.lang.String key) {
		set("key", key);
	}
	
	/**
	 * 表单key
	 */
	public java.lang.String getKey() {
		return getStr("key");
	}

	/**
	 * 表单value
	 */
	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	/**
	 * 表单value
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 表单信息类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 表单信息类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

}
