package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLotteryLog<M extends BaseLotteryLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setLotteryId(java.lang.Integer lotteryId) {
		set("lottery_id", lotteryId);
	}
	
	public java.lang.Integer getLotteryId() {
		return getInt("lottery_id");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 0待开奖 1未中奖 2中奖3已领取
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 0待开奖 1未中奖 2中奖3已领取
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	/**
	 * 领取时间
	 */
	public void setRaffleTime(java.lang.Integer raffleTime) {
		set("raffle_time", raffleTime);
	}
	
	/**
	 * 领取时间
	 */
	public java.lang.Integer getRaffleTime() {
		return getInt("raffle_time");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setObtainTime(java.lang.Integer obtainTime) {
		set("obtain_time", obtainTime);
	}
	
	public java.lang.Integer getObtainTime() {
		return getInt("obtain_time");
	}

	public void setFormId(java.lang.String formId) {
		set("form_id", formId);
	}
	
	public java.lang.String getFormId() {
		return getStr("form_id");
	}

	/**
	 * 下级用户
	 */
	public void setChildId(java.lang.Integer childId) {
		set("child_id", childId);
	}
	
	/**
	 * 下级用户
	 */
	public java.lang.Integer getChildId() {
		return getInt("child_id");
	}

	/**
	 * 幸运码
	 */
	public void setLuckyCode(java.lang.String luckyCode) {
		set("lucky_code", luckyCode);
	}
	
	/**
	 * 幸运码
	 */
	public java.lang.String getLuckyCode() {
		return getStr("lucky_code");
	}

}
