package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBargainOrder<M extends BaseBargainOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 商品售价
	 */
	public void setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
	}
	
	/**
	 * 商品售价
	 */
	public java.math.BigDecimal getOriginalPrice() {
		return get("original_price");
	}

	/**
	 * 商品最低价
	 */
	public void setMinPrice(java.math.BigDecimal minPrice) {
		set("min_price", minPrice);
	}
	
	/**
	 * 商品最低价
	 */
	public java.math.BigDecimal getMinPrice() {
		return get("min_price");
	}

	/**
	 * 砍价时间
	 */
	public void setTime(java.lang.Integer time) {
		set("time", time);
	}
	
	/**
	 * 砍价时间
	 */
	public java.lang.Integer getTime() {
		return getInt("time");
	}

	/**
	 * 状态 0--进行中 1--成功 2--失败
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 0--进行中 1--成功 2--失败
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	/**
	 * 砍价方式数据
	 */
	public void setStatusData(java.lang.String statusData) {
		set("status_data", statusData);
	}
	
	/**
	 * 砍价方式数据
	 */
	public java.lang.String getStatusData() {
		return getStr("status_data");
	}

}
