package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntegralLog<M extends BaseIntegralLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * 描述
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 积分
	 */
	public void setIntegral(java.lang.Long integral) {
		set("integral", integral);
	}
	
	/**
	 * 积分
	 */
	public java.lang.Long getIntegral() {
		return getLong("integral");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.lang.Long addtime) {
		set("addtime", addtime);
	}
	
	/**
	 * 添加时间
	 */
	public java.lang.Long getAddtime() {
		return getLong("addtime");
	}

	/**
	 * 用户名
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 操作者
	 */
	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}
	
	/**
	 * 操作者
	 */
	public java.lang.String getOperator() {
		return getStr("operator");
	}

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

	/**
	 * 分销商id
	 */
	public void setOperatorId(java.lang.Long operatorId) {
		set("operator_id", operatorId);
	}
	
	/**
	 * 分销商id
	 */
	public java.lang.Long getOperatorId() {
		return getLong("operator_id");
	}

	/**
	 * 数据类型 0--积分修改 1--余额修改
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 数据类型 0--积分修改 1--余额修改
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
	}
	
	public java.lang.String getPicUrl() {
		return getStr("pic_url");
	}

	public void setExplain(java.lang.String explain) {
		set("explain", explain);
	}
	
	public java.lang.String getExplain() {
		return getStr("explain");
	}

}
