package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsGoods<M extends BaseMsGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 商品名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 原价
	 */
	public void setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
	}
	
	/**
	 * 原价
	 */
	public java.math.BigDecimal getOriginalPrice() {
		return get("original_price");
	}

	/**
	 * 商品详情，图文
	 */
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	/**
	 * 商品详情，图文
	 */
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	/**
	 * 上架状态【1=> 上架，2=> 下架】
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 上架状态【1=> 上架，2=> 下架】
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 服务选项
	 */
	public void setService(java.lang.String service) {
		set("service", service);
	}
	
	/**
	 * 服务选项
	 */
	public java.lang.String getService() {
		return getStr("service");
	}

	/**
	 * 商品排序 升序
	 */
	public void setSort(java.lang.Long sort) {
		set("sort", sort);
	}
	
	/**
	 * 商品排序 升序
	 */
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	/**
	 * 虚拟销量
	 */
	public void setVirtualSales(java.lang.Long virtualSales) {
		set("virtual_sales", virtualSales);
	}
	
	/**
	 * 虚拟销量
	 */
	public java.lang.Long getVirtualSales() {
		return getLong("virtual_sales");
	}

	/**
	 * 商品缩略图
	 */
	public void setCoverPic(java.lang.String coverPic) {
		set("cover_pic", coverPic);
	}
	
	/**
	 * 商品缩略图
	 */
	public java.lang.String getCoverPic() {
		return getStr("cover_pic");
	}

	/**
	 * 添加时间
	 */
	public void setAddtime(java.lang.Long addtime) {
		set("addtime", addtime);
	}
	
	/**
	 * 添加时间
	 */
	public java.lang.Long getAddtime() {
		return getLong("addtime");
	}

	/**
	 * 是否删除
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 实际销量
	 */
	public void setSales(java.lang.Long sales) {
		set("sales", sales);
	}
	
	/**
	 * 实际销量
	 */
	public java.lang.Long getSales() {
		return getLong("sales");
	}

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

	public void setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
	}
	
	public java.lang.String getVideoUrl() {
		return getStr("video_url");
	}

	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	/**
	 * 重量
	 */
	public void setWeight(java.lang.Double weight) {
		set("weight", weight);
	}
	
	/**
	 * 重量
	 */
	public java.lang.Double getWeight() {
		return getDouble("weight");
	}

	/**
	 * 运费模板ID
	 */
	public void setFreight(java.lang.Long freight) {
		set("freight", freight);
	}
	
	/**
	 * 运费模板ID
	 */
	public java.lang.Long getFreight() {
		return getLong("freight");
	}

	/**
	 * 满减
	 */
	public void setFullCut(java.lang.String fullCut) {
		set("full_cut", fullCut);
	}
	
	/**
	 * 满减
	 */
	public java.lang.String getFullCut() {
		return getStr("full_cut");
	}

	/**
	 * 积分设置
	 */
	public void setIntegral(java.lang.String integral) {
		set("integral", integral);
	}
	
	/**
	 * 积分设置
	 */
	public java.lang.String getIntegral() {
		return getStr("integral");
	}

	/**
	 * 是否使用规格：0=不使用，1=使用
	 */
	public void setUseAttr(java.lang.Integer useAttr) {
		set("use_attr", useAttr);
	}
	
	/**
	 * 是否使用规格：0=不使用，1=使用
	 */
	public java.lang.Integer getUseAttr() {
		return getInt("use_attr");
	}

	/**
	 * 规格的库存及价格
	 */
	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	/**
	 * 规格的库存及价格
	 */
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	/**
	 * 是否支持会员折扣
	 */
	public void setIsDiscount(java.lang.Integer isDiscount) {
		set("is_discount", isDiscount);
	}
	
	/**
	 * 是否支持会员折扣
	 */
	public java.lang.Integer getIsDiscount() {
		return getInt("is_discount");
	}

	/**
	 * 是否支持优惠劵
	 */
	public void setCoupon(java.lang.Integer coupon) {
		set("coupon", coupon);
	}
	
	/**
	 * 是否支持优惠劵
	 */
	public java.lang.Integer getCoupon() {
		return getInt("coupon");
	}

	/**
	 * 支付方式
	 */
	public void setPayment(java.lang.String payment) {
		set("payment", payment);
	}
	
	/**
	 * 支付方式
	 */
	public java.lang.String getPayment() {
		return getStr("payment");
	}

	/**
	 * 是否单独分销设置：0=否，1=是
	 */
	public void setIndividualShare(java.lang.Integer individualShare) {
		set("individual_share", individualShare);
	}
	
	/**
	 * 是否单独分销设置：0=否，1=是
	 */
	public java.lang.Integer getIndividualShare() {
		return getInt("individual_share");
	}

	/**
	 * 一级分销佣金比例
	 */
	public void setShareCommissionFirst(java.math.BigDecimal shareCommissionFirst) {
		set("share_commission_first", shareCommissionFirst);
	}
	
	/**
	 * 一级分销佣金比例
	 */
	public java.math.BigDecimal getShareCommissionFirst() {
		return get("share_commission_first");
	}

	/**
	 * 二级分销佣金比例
	 */
	public void setShareCommissionSecond(java.math.BigDecimal shareCommissionSecond) {
		set("share_commission_second", shareCommissionSecond);
	}
	
	/**
	 * 二级分销佣金比例
	 */
	public java.math.BigDecimal getShareCommissionSecond() {
		return get("share_commission_second");
	}

	/**
	 * 三级分销佣金比例
	 */
	public void setShareCommissionThird(java.math.BigDecimal shareCommissionThird) {
		set("share_commission_third", shareCommissionThird);
	}
	
	/**
	 * 三级分销佣金比例
	 */
	public java.math.BigDecimal getShareCommissionThird() {
		return get("share_commission_third");
	}

	/**
	 * 佣金配比 0--百分比 1--固定金额
	 */
	public void setShareType(java.lang.Integer shareType) {
		set("share_type", shareType);
	}
	
	/**
	 * 佣金配比 0--百分比 1--固定金额
	 */
	public java.lang.Integer getShareType() {
		return getInt("share_type");
	}

	/**
	 * 自购返利
	 */
	public void setRebate(java.math.BigDecimal rebate) {
		set("rebate", rebate);
	}
	
	/**
	 * 自购返利
	 */
	public java.math.BigDecimal getRebate() {
		return get("rebate");
	}

	/**
	 * 分销设置类型 0.普通设置|1.详细设置
	 */
	public void setAttrSettingType(java.lang.Boolean attrSettingType) {
		set("attr_setting_type", attrSettingType);
	}
	
	/**
	 * 分销设置类型 0.普通设置|1.详细设置
	 */
	public java.lang.Boolean getAttrSettingType() {
		return get("attr_setting_type");
	}

}
