package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShop<M extends BaseShop<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
	}
	
	public java.lang.String getLongitude() {
		return getStr("longitude");
	}

	public void setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
	}
	
	public java.lang.String getLatitude() {
		return getStr("latitude");
	}

	/**
	 * 评分 1~5
	 */
	public void setScore(java.lang.Integer score) {
		set("score", score);
	}
	
	/**
	 * 评分 1~5
	 */
	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public void setCoverUrl(java.lang.String coverUrl) {
		set("cover_url", coverUrl);
	}
	
	public java.lang.String getCoverUrl() {
		return getStr("cover_url");
	}

	public void setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
	}
	
	public java.lang.String getPicUrl() {
		return getStr("pic_url");
	}

	/**
	 * 营业时间
	 */
	public void setShopTime(java.lang.String shopTime) {
		set("shop_time", shopTime);
	}
	
	/**
	 * 营业时间
	 */
	public java.lang.String getShopTime() {
		return getStr("shop_time");
	}

	/**
	 * 门店介绍
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 门店介绍
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 是否设为默认 0--否 1--是 （只能设置一个门店为默认门店）
	 */
	public void setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
	}
	
	/**
	 * 是否设为默认 0--否 1--是 （只能设置一个门店为默认门店）
	 */
	public java.lang.Integer getIsDefault() {
		return getInt("is_default");
	}

}
