package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYyOrderForm<M extends BaseYyOrderForm<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

	public void setGoodsId(java.lang.Long goodsId) {
		set("goods_id", goodsId);
	}
	
	public java.lang.Long getGoodsId() {
		return getLong("goods_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	public void setKey(java.lang.String key) {
		set("key", key);
	}
	
	public java.lang.String getKey() {
		return getStr("key");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setIsDelete(java.lang.Long isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Long getIsDelete() {
		return getLong("is_delete");
	}

	public void setAddtime(java.lang.Long addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Long getAddtime() {
		return getLong("addtime");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

}
