package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLotteryGoods<M extends BaseLotteryGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 开始时间
	 */
	public void setStartTime(java.lang.Integer startTime) {
		set("start_time", startTime);
	}
	
	/**
	 * 开始时间
	 */
	public java.lang.Integer getStartTime() {
		return getInt("start_time");
	}

	/**
	 * 结束时间
	 */
	public void setEndTime(java.lang.Integer endTime) {
		set("end_time", endTime);
	}
	
	/**
	 * 结束时间
	 */
	public java.lang.Integer getEndTime() {
		return getInt("end_time");
	}

	/**
	 * 数量
	 */
	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}
	
	/**
	 * 数量
	 */
	public java.lang.Integer getStock() {
		return getInt("stock");
	}

	/**
	 * 规格
	 */
	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	/**
	 * 规格
	 */
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 是否关闭
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 是否关闭
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.lang.Integer getUpdateTime() {
		return getInt("update_time");
	}

	/**
	 * 0未完成 1已完成
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 0未完成 1已完成
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
