package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMiaoshaGoods<M extends BaseMiaoshaGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 开始时间：0~23
	 */
	public void setStartTime(java.lang.Integer startTime) {
		set("start_time", startTime);
	}
	
	/**
	 * 开始时间：0~23
	 */
	public java.lang.Integer getStartTime() {
		return getInt("start_time");
	}

	/**
	 * 开放日期，例：2017-08-21
	 */
	public void setOpenDate(java.util.Date openDate) {
		set("open_date", openDate);
	}
	
	/**
	 * 开放日期，例：2017-08-21
	 */
	public java.util.Date getOpenDate() {
		return get("open_date");
	}

	/**
	 * 规格秒杀价数量
	 */
	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	/**
	 * 规格秒杀价数量
	 */
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 限购数量，0=不限购
	 */
	public void setBuyMax(java.lang.Integer buyMax) {
		set("buy_max", buyMax);
	}
	
	/**
	 * 限购数量，0=不限购
	 */
	public java.lang.Integer getBuyMax() {
		return getInt("buy_max");
	}

	/**
	 * 限单
	 */
	public void setBuyLimit(java.lang.Long buyLimit) {
		set("buy_limit", buyLimit);
	}
	
	/**
	 * 限单
	 */
	public java.lang.Long getBuyLimit() {
		return getLong("buy_limit");
	}

	/**
	 * 是否享受会员折扣 0-不享受 1--享受
	 */
	public void setIsLevel(java.lang.Boolean isLevel) {
		set("is_level", isLevel);
	}
	
	/**
	 * 是否享受会员折扣 0-不享受 1--享受
	 */
	public java.lang.Boolean getIsLevel() {
		return get("is_level");
	}

}
