package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCoupon<M extends BaseCoupon<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 优惠券名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 优惠券名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public void setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
	}
	
	public java.lang.String getPicUrl() {
		return getStr("pic_url");
	}

	/**
	 * 优惠券类型：1=折扣，2=满减
	 */
	public void setDiscountType(java.lang.Integer discountType) {
		set("discount_type", discountType);
	}
	
	/**
	 * 优惠券类型：1=折扣，2=满减
	 */
	public java.lang.Integer getDiscountType() {
		return getInt("discount_type");
	}

	/**
	 * 最低消费金额
	 */
	public void setMinPrice(java.math.BigDecimal minPrice) {
		set("min_price", minPrice);
	}
	
	/**
	 * 最低消费金额
	 */
	public java.math.BigDecimal getMinPrice() {
		return get("min_price");
	}

	/**
	 * 优惠金额
	 */
	public void setSubPrice(java.math.BigDecimal subPrice) {
		set("sub_price", subPrice);
	}
	
	/**
	 * 优惠金额
	 */
	public java.math.BigDecimal getSubPrice() {
		return get("sub_price");
	}

	/**
	 * 折扣率
	 */
	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	/**
	 * 折扣率
	 */
	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	/**
	 * 到期类型：1=领取后N天过期，2=指定有效期
	 */
	public void setExpireType(java.lang.Integer expireType) {
		set("expire_type", expireType);
	}
	
	/**
	 * 到期类型：1=领取后N天过期，2=指定有效期
	 */
	public java.lang.Integer getExpireType() {
		return getInt("expire_type");
	}

	/**
	 * 有效天数，expire_type=1时
	 */
	public void setExpireDay(java.lang.Integer expireDay) {
		set("expire_day", expireDay);
	}
	
	/**
	 * 有效天数，expire_type=1时
	 */
	public java.lang.Integer getExpireDay() {
		return getInt("expire_day");
	}

	/**
	 * 有效期开始时间
	 */
	public void setBeginTime(java.lang.Integer beginTime) {
		set("begin_time", beginTime);
	}
	
	/**
	 * 有效期开始时间
	 */
	public java.lang.Integer getBeginTime() {
		return getInt("begin_time");
	}

	/**
	 * 有效期结束时间
	 */
	public void setEndTime(java.lang.Integer endTime) {
		set("end_time", endTime);
	}
	
	/**
	 * 有效期结束时间
	 */
	public java.lang.Integer getEndTime() {
		return getInt("end_time");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	/**
	 * 发放总数量
	 */
	public void setTotalCount(java.lang.Integer totalCount) {
		set("total_count", totalCount);
	}
	
	/**
	 * 发放总数量
	 */
	public java.lang.Integer getTotalCount() {
		return getInt("total_count");
	}

	/**
	 * 是否加入领券中心 1--不加入领券中心 2--加入领券中心
	 */
	public void setIsJoin(java.lang.Integer isJoin) {
		set("is_join", isJoin);
	}
	
	/**
	 * 是否加入领券中心 1--不加入领券中心 2--加入领券中心
	 */
	public java.lang.Integer getIsJoin() {
		return getInt("is_join");
	}

	/**
	 * 排序按升序排列
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序按升序排列
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setCatIdList(java.lang.String catIdList) {
		set("cat_id_list", catIdList);
	}
	
	public java.lang.String getCatIdList() {
		return getStr("cat_id_list");
	}

	public void setAppointType(java.lang.Boolean appointType) {
		set("appoint_type", appointType);
	}
	
	public java.lang.Boolean getAppointType() {
		return get("appoint_type");
	}

	/**
	 * 是否加入积分商城 1--不加入 2--加入
	 */
	public void setIsIntegral(java.lang.Integer isIntegral) {
		set("is_integral", isIntegral);
	}
	
	/**
	 * 是否加入积分商城 1--不加入 2--加入
	 */
	public java.lang.Integer getIsIntegral() {
		return getInt("is_integral");
	}

	/**
	 * 兑换需要积分数量
	 */
	public void setIntegral(java.lang.Integer integral) {
		set("integral", integral);
	}
	
	/**
	 * 兑换需要积分数量
	 */
	public java.lang.Integer getIntegral() {
		return getInt("integral");
	}

	/**
	 * 售价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 售价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 积分商城发放总数
	 */
	public void setTotalNum(java.lang.Integer totalNum) {
		set("total_num", totalNum);
	}
	
	/**
	 * 积分商城发放总数
	 */
	public java.lang.Integer getTotalNum() {
		return getInt("total_num");
	}

	/**
	 * 每人限制兑换数量
	 */
	public void setUserNum(java.lang.Integer userNum) {
		set("user_num", userNum);
	}
	
	/**
	 * 每人限制兑换数量
	 */
	public java.lang.Integer getUserNum() {
		return getInt("user_num");
	}

	/**
	 * 使用说明
	 */
	public void setRule(java.lang.String rule) {
		set("rule", rule);
	}
	
	/**
	 * 使用说明
	 */
	public java.lang.String getRule() {
		return getStr("rule");
	}

	public void setGoodsIdList(java.lang.String goodsIdList) {
		set("goods_id_list", goodsIdList);
	}
	
	public java.lang.String getGoodsIdList() {
		return getStr("goods_id_list");
	}

}
