package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtGoodsDetail<M extends BasePtGoodsDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 团长优惠
	 */
	public void setColonel(java.math.BigDecimal colonel) {
		set("colonel", colonel);
	}
	
	/**
	 * 团长优惠
	 */
	public java.math.BigDecimal getColonel() {
		return get("colonel");
	}

	/**
	 * 商品成团数
	 */
	public void setGroupNum(java.lang.Long groupNum) {
		set("group_num", groupNum);
	}
	
	/**
	 * 商品成团数
	 */
	public java.lang.Long getGroupNum() {
		return getLong("group_num");
	}

	/**
	 * 拼团时间/小时
	 */
	public void setGroupTime(java.lang.Integer groupTime) {
		set("group_time", groupTime);
	}
	
	/**
	 * 拼团时间/小时
	 */
	public java.lang.Integer getGroupTime() {
		return getInt("group_time");
	}

	/**
	 * 规格的库存及价格
	 */
	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	/**
	 * 规格的库存及价格
	 */
	public java.lang.String getAttr() {
		return getStr("attr");
	}

	/**
	 * 是否享受会员折扣 0-不享受 1--享受
	 */
	public void setIsLevel(java.lang.Boolean isLevel) {
		set("is_level", isLevel);
	}
	
	/**
	 * 是否享受会员折扣 0-不享受 1--享受
	 */
	public java.lang.Boolean getIsLevel() {
		return get("is_level");
	}

}
