package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDiyTemplate<M extends BaseDiyTemplate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 模板名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 模板名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 模板数据
	 */
	public void setTemplate(java.lang.String template) {
		set("template", template);
	}
	
	/**
	 * 模板数据
	 */
	public java.lang.String getTemplate() {
		return getStr("template");
	}

	public void setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}
	
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

}
