package com.yoyound.sync.data.test;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setExpire(java.lang.Integer expire) {
		set("expire", expire);
	}
	
	public java.lang.Integer getExpire() {
		return getInt("expire");
	}

	public void setData(java.lang.String data) {
		set("data", data);
	}
	
	public java.lang.String getData() {
		return getStr("data");
	}

}
